'use client';

import { useEffect, useMemo, useState } from 'react';
import { Bell, BookOpen, Bus, CheckCircle2, ClipboardCheck, FileText, IdCard, MessageSquare, Package, Plus, Send, ShieldCheck, UserRound, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';

type ServiceTab = 'Approvals'|'Requests'|'Announcements'|'Forms'|'ID Cards'|'Library Suggestions'|'Lab Purchases'|'Policies'|'Services'|'Feedback'|'Emergency Contacts';
type Item = { id:string; title:string; type:string; student:string; module:string; status:string; priority?:string; date:string; detail:string };
const seed: Item[] = [
  {id:'APR-2048',title:'Staff leave request',type:'Staff Leave',student:'—',module:'Administration',status:'Awaiting Review',priority:'High',date:'2026-09-09',detail:'Maya Iyer · 14 Sep · Physics cover required.'},
  {id:'ABS-1048',title:'Absence request',type:'Absence',student:'Nithin Selvaraj',module:'Attendance',status:'Under Review',date:'2026-09-09',detail:'14 Sep · Full day · Appointment.'},
  {id:'LBS-0148',title:'Introduction to Robotics',type:'Book Suggestion',student:'Nithin Selvaraj',module:'Library',status:'Purchase Requested',date:'2026-09-08',detail:'Requested for independent study and robotics project.'},
  {id:'LPR-0842',title:'Digital multimeter × 5',type:'Lab Purchase',student:'—',module:'Laboratory',status:'Submitted',priority:'High',date:'2026-09-08',detail:'Physics Lab · Required for circuits practical.'},
];
const tabsByRole: Record<string, ServiceTab[]> = { Admin:['Approvals','Announcements','Forms','ID Cards','Lab Purchases','Policies','Services','Feedback','Emergency Contacts'], 'Head of School':['Approvals','Announcements','Policies','Services','Feedback'], Student:['Requests','Announcements','Forms','ID Cards','Library Suggestions','Policies','Services','Feedback','Emergency Contacts'], Teacher:['Announcements','Forms','Lab Purchases','Policies','Services','Feedback'] };

export function StudentServices({ ws, role, initialTab }: { ws:any; role:string; initialTab?:ServiceTab }) {
  const tabs = tabsByRole[role] || ['Announcements','Policies','Services'];
  const [tab,setTab] = useState<ServiceTab>(initialTab && tabs.includes(initialTab) ? initialTab : tabs[0]);
  // Keep the visible section in sync with sidebar navigation. The services
  // shell stays mounted while its route changes, so relying on the initial
  // state alone makes the first click appear to do nothing.
  useEffect(() => {
    if (initialTab && tabs.includes(initialTab)) setTab(initialTab);
  }, [initialTab, tabs]);
  const [items,setItems] = useState(seed);
  const [query,setQuery] = useState('');
  const [message,setMessage] = useState('');
  const [showForm,setShowForm] = useState(false);
  useEffect(()=>{let cancelled=false;fetch('/api/cross-workflows',{credentials:'same-origin'}).then(async response=>response.ok?response.json():Promise.reject(await response.json())).then((data:any)=>{if(cancelled)return;const parentItems=(data.parentRequests||[]).map((request:any):Item=>({id:request.id,title:`${request.request_type.replace(/([A-Z])/g,' $1').trim()} request`,type:'Parent Request',student:request.student_id,module:'Student Services',status:request.status,priority:'Normal',date:request.request_date,detail:request.reason||request.notes||'Parent operational request.'}));const approvalItems=(data.approvals||[]).map((approval:any):Item=>({id:approval.id,title:approval.title,type:approval.source_type,student:approval.student_id||'—',module:approval.module,status:approval.status,priority:approval.priority,date:approval.created_at?.slice(0,10)||'',detail:'Shared approval record.'}));if(parentItems.length||approvalItems.length)setItems((current)=>[...parentItems,...approvalItems,...current.filter((item)=>!parentItems.some((next:Item)=>next.id===item.id)&&!approvalItems.some((next:Item)=>next.id===item.id))]);}).catch(()=>undefined);return()=>{cancelled=true};},[]);
  const visible = useMemo(() => items.filter((item) => `${item.title} ${item.type} ${item.student} ${item.module} ${item.status}`.toLowerCase().includes(query.toLowerCase())),[items,query]);
  const act = (item:Item,status:string) => { setItems((all)=>all.map((x)=>x.id===item.id?{...x,status}:x)); setMessage(`${item.id} marked ${status}.`); if(item.type==='Parent Request')void fetch('/api/cross-workflows',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'parentRequest.update',data:{id:item.id,status}})}).then(async response=>{if(!response.ok){const problem:any=await response.json().catch(()=>({}));setMessage(problem.error||'The request could not be updated.');}}).catch(()=>undefined); };
  const create = (type:string,title:string,module:string) => { const id=`REQ-${String(Date.now()).slice(-6)}`; setItems((all)=>[{id,title,type,student:ws?.member?.name||'Nithin Selvaraj',module,status:'Submitted',date:new Date().toISOString().slice(0,10),detail:'Submitted from SchoolOS Student Services.'},...all]); setShowForm(false); setMessage(`${type} submitted.`); };
  return <section className="services-page"><div className="page-heading"><div><div className="eyebrow">SCHOOL SERVICES</div><h1>{role==='Admin'||role==='Head of School'?'Approvals & services':'Student services'}</h1><p>Requests, communications and school support in one place.</p></div><Button onClick={()=>setShowForm(true)}><Plus size={16}/> New request</Button></div>{message&&<p className="student-success" role="status">{message}</p>}<nav className="services-tabs" aria-label="Student services sections">{tabs.map((name)=><button key={name} className={tab===name?'active':''} onClick={()=>setTab(name)}>{name}</button>)}</nav>{['Approvals','Requests','Lab Purchases','Library Suggestions','Feedback','Forms','ID Cards','Emergency Contacts'].includes(tab)&&<div className="services-toolbar"><Input placeholder="Search requests and records…" value={query} onChange={(e)=>setQuery(e.target.value)}/><span>{visible.length} records</span></div>}
    {['Approvals','Requests','Lab Purchases','Library Suggestions','Feedback'].includes(tab)&&<div className="services-grid">{visible.filter((item)=>tab==='Approvals'?true:tab==='Requests'?(item.type.toLowerCase().includes('request')||['Absence','Early Departure','Information Change','ID Replacement'].includes(item.type)):tab==='Lab Purchases'?item.type==='Lab Purchase':tab==='Library Suggestions'?item.type==='Book Suggestion':item.type==='Feedback').map((item)=><article className="service-record panel" key={item.id}><div className="service-record-top"><span className="service-icon"><ClipboardCheck size={17}/></span><span><b>{item.title}</b><small>{item.id} · {item.module} · {item.date}</small></span><span className={`service-status ${item.status.toLowerCase().replaceAll(' ','-')}`}>{item.status}</span></div><p>{item.detail}</p>{item.priority&&<span className="service-priority">{item.priority} priority</span>}<div className="service-actions">{(role==='Admin'||role==='Head of School')&&<><Button size="sm" onClick={()=>act(item,'Approved')}>Approve</Button><Button size="sm" variant="outline" onClick={()=>act(item,'Rejected')}>Reject</Button></>}<Button size="sm" variant="ghost" onClick={()=>setMessage(`${item.id} opened`)}>Open detail</Button></div></article>)}</div>}
    {tab==='Announcements'&&<div className="services-grid"><article className="service-record panel announcement-card"><div className="service-record-top"><span className="service-icon"><Bell size={17}/></span><span><b>Grade 12 Assembly</b><small>Head of School · Today, 10:42 · Grade 12</small></span><span className="service-status important">Important</span></div><p>Grade 12 students should report to the auditorium during Period 2.</p><Button size="sm" onClick={()=>setMessage('Announcement acknowledged')}>Acknowledge</Button></article><article className="service-record panel"><div className="service-record-top"><span className="service-icon"><Bell size={17}/></span><span><b>Library hours update</b><small>School Office · 2026-09-09 · Entire school</small></span></div><p>Normal borrowing and returns are available until 4:00 PM today.</p></article>{(role==='Admin'||role==='Head of School'||role==='Teacher')&&<Button onClick={()=>create('Announcement','New school announcement','Communication')}><Send size={15}/> Publish announcement</Button>}</div>}
    {tab==='Forms'&&<div className="services-grid"><article className="service-record panel"><div className="service-record-top"><span className="service-icon"><FileText size={17}/></span><span><b>Competition Registration</b><small>Open until 2026-09-20 · Approval required</small></span></div><p>Register for competitions, add a teacher and submit supporting notes.</p><Button size="sm" onClick={()=>create('Competition Registration','Competition Registration','Forms')}>Submit form</Button></article><article className="service-record panel"><div className="service-record-top"><span className="service-icon"><FileText size={17}/></span><span><b>General School Request</b><small>Available to students and staff</small></span></div><p>Send a structured request to the school administration.</p><Button size="sm" onClick={()=>create('General Request','General School Request','Forms')}>Open form</Button></article></div>}
    {tab==='ID Cards'&&<div className="services-grid"><article className="service-record panel"><div className="service-record-top"><span className="service-icon"><IdCard size={17}/></span><span><b>School ID · Nithin Selvaraj</b><small>Student ID STU-001 · DP-2 · 2026–27</small></span><span className="service-status approved">Active</span></div><p>Your school identification card is active. Report it lost or damaged to request a replacement.</p><div className="service-actions"><Button size="sm" variant="outline" onClick={()=>create('ID Replacement','ID replacement request','Administration')}>Request replacement</Button><Button size="sm" variant="ghost" onClick={()=>setMessage('ID marked as lost')}>Report lost</Button></div></article></div>}
    {tab==='Policies'&&<div className="services-grid"><article className="service-record panel"><div className="service-record-top"><span className="service-icon"><ShieldCheck size={17}/></span><span><b>Library Borrowing Policy</b><small>Library · Version 2 · Effective 2026-08-01</small></span></div><p>Books are due on the date shown in your loan record. Report loss or damage to the library team promptly.</p><Button size="sm" variant="outline" onClick={()=>setMessage('Policy opened')}>Read policy</Button></article><article className="service-record panel"><div className="service-record-top"><span className="service-icon"><ShieldCheck size={17}/></span><span><b>Student Conduct Handbook</b><small>Student Conduct · Published</small></span></div><p>School expectations, support pathways and restorative processes.</p></article></div>}
    {tab==='Services'&&<div className="service-status-grid">{[['Library','Available','Open today 08:00–16:00',BookOpen],['Chemistry Laboratory','Limited Service','Chemical issue desk unavailable during Period 4.',Package],['Transport Office','Available','Normal operations today.',Bus],['School Office','Available','Reception open 08:00–16:30.',UserRound]].map(([title,status,note,Icon]:any)=><article className="service-record panel" key={title}><div className="service-record-top"><span className="service-icon"><Icon size={17}/></span><span><b>{title}</b><small>{status}</small></span></div><p>{note}</p><Button size="sm" variant="outline" onClick={()=>setMessage(`${title} opened`)}>Open {title}</Button></article>)}</div>}
    {tab==='Emergency Contacts'&&<div className="service-record panel emergency-card"><div className="service-record-top"><span className="service-icon"><UserRound size={17}/></span><span><b>Emergency Contacts</b><small>Visible only to authorized school roles</small></span></div><p>Primary: Priya Selvaraj · Parent / Guardian · +91 98765 10001</p><p>Secondary: Arun Selvaraj · Parent / Guardian · +91 98765 10002</p><Button size="sm" variant="outline" onClick={()=>setMessage('Change request started')}>Request a change</Button></div>}
    {showForm&&<div className="services-dialog"><div className="services-modal"><div className="service-record-top"><span><b>New service request</b><small>Select a request type for {ws?.member?.name||'your student profile'}.</small></span><Button variant="ghost" onClick={()=>setShowForm(false)} aria-label="Close"><X size={17}/></Button></div><div className="service-form-actions"><Button onClick={()=>create('Absence','Absence request','Attendance')}>Absence / leave</Button><Button onClick={()=>create('Early Departure','Early departure request','Attendance')}>Early departure</Button><Button onClick={()=>create('Feedback','Feedback / suggestion','Student Services')}>Feedback</Button><Button onClick={()=>create('Information Change','Information change request','Student Records')}>Information change</Button><Button onClick={()=>create('Book Suggestion','Suggest a library book','Library')}>Suggest a book</Button><Button onClick={()=>create('Lab Purchase','Lab purchase request','Laboratory')}>Lab purchase</Button></div></div></div>}
  </section>;
}
