export type Entry = {
  id: string;
  kind: string;
  name: string;
  quantity: number;
  data: any;
  version?: number;
};
export const classes = [
  'Physics',
  'Chemistry',
  'Digital Society',
  'Math AA',
  'English',
  'French B',
];
export const students = [
  'Nithin Selvaraj',
  'Emma Wilson',
  'Liam Chen',
  'Sofia Martinez',
  'Noah Patel',
  'Isabella Brown',
  'Oliver Kim',
  'Mia Thompson',
  'Ethan Davis',
  'Amelia Singh',
  'Lucas Garcia',
  'Charlotte Lee',
  'Mason Anderson',
  'Harper Clark',
  'Logan Robinson',
  'Evelyn Lewis',
  'Alexander Walker',
  'Aria Hall',
  'James Allen',
  'Scarlett Young',
  'Benjamin King',
  'Chloe Wright',
  'Henry Scott',
  'Grace Green',
  'Daniel Adams',
  'Lily Baker',
  'Samuel Nelson',
  'Zoe Carter',
  'Jacob Mitchell',
  'Nora Roberts',
];
const chem = [
  'Sodium chloride',
  'Hydrochloric acid',
  'Copper sulfate',
  'Ethanol',
  'Distilled water',
  'Sodium hydroxide',
  'Beaker · 250 mL',
  'Conical flask · 100 mL',
  'Volumetric flask',
  'Measuring cylinder',
  'Burette · 50 mL',
  'Glass pipette',
  'Test tubes',
  'Bunsen burner',
  'Digital balance',
  'Safety goggles',
  'Lab coats',
  'Nitrile gloves',
  'Universal indicator',
  'Wash bottle',
];
const physics = [
  'Digital multimeter',
  'DC power supply',
  'Connecting leads',
  'Resistor set',
  'Ammeter',
  'Voltmeter',
  'Dynamics trolley',
  'Air track',
  'Pulley set',
  'Slotted masses',
  'Convex lens',
  'Concave mirror',
  'Optical bench',
  'Laser ray box',
  'Thermometer',
  'Calorimeter',
  'Tuning forks',
  'Oscilloscope',
  'Vernier caliper',
  'Micrometer',
];
const bio = [
  'Compound microscope',
  'Microscope slides',
  'Cover slips',
  'Prepared cell slides',
  'Petri dishes',
  'Dissection kit',
  'Forceps',
  'Scalpel',
  'Human skeleton model',
  'Heart model',
  'Leaf specimens',
  'Seed collection',
  'Agar powder',
  'Methylene blue',
  'Iodine solution',
  'Dropper',
  'Incubator',
  'Pipette tips',
  'Safety goggles',
  'Specimen jars',
];
const titles = [
  ['A Brief History of Time', 'Stephen Hawking'],
  ['The Gene', 'Siddhartha Mukherjee'],
  ['To Kill a Mockingbird', 'Harper Lee'],
  ['The Great Gatsby', 'F. Scott Fitzgerald'],
  ['Sapiens', 'Yuval Noah Harari'],
  ['Silent Spring', 'Rachel Carson'],
  ['The Selfish Gene', 'Richard Dawkins'],
  ['Cosmos', 'Carl Sagan'],
  ['1984', 'George Orwell'],
  ['Pride and Prejudice', 'Jane Austen'],
  ['Thinking, Fast and Slow', 'Daniel Kahneman'],
  ['The Alchemist', 'Paulo Coelho'],
  ['The Book Thief', 'Markus Zusak'],
  ['The Kite Runner', 'Khaled Hosseini'],
  ['Educated', 'Tara Westover'],
  ['Fahrenheit 451', 'Ray Bradbury'],
  ['Brave New World', 'Aldous Huxley'],
  ['Animal Farm', 'George Orwell'],
  ['Jane Eyre', 'Charlotte Brontë'],
  ['Frankenstein', 'Mary Shelley'],
  ['The Odyssey', 'Homer'],
  ['Hamlet', 'William Shakespeare'],
  ['Macbeth', 'William Shakespeare'],
  ['Things Fall Apart', 'Chinua Achebe'],
  ['The Namesake', 'Jhumpa Lahiri'],
  ['Life of Pi', 'Yann Martel'],
  ['The Catcher in the Rye', 'J. D. Salinger'],
  ['The Little Prince', 'Antoine de Saint-Exupéry'],
  ['A Short History of Nearly Everything', 'Bill Bryson'],
  ['Surely You’re Joking, Mr. Feynman!', 'Richard Feynman'],
  ['The Double Helix', 'James Watson'],
  ['The Origin of Species', 'Charles Darwin'],
  ['The Immortal Life of Henrietta Lacks', 'Rebecca Skloot'],
  ['Astrophysics for People in a Hurry', 'Neil deGrasse Tyson'],
  ['The Elegant Universe', 'Brian Greene'],
  ['Freakonomics', 'Steven Levitt'],
  ['The Undercover Economist', 'Tim Harford'],
  ['Development as Freedom', 'Amartya Sen'],
  ['Doughnut Economics', 'Kate Raworth'],
  ['The Wealth of Nations', 'Adam Smith'],
  ['How Not to Be Wrong', 'Jordan Ellenberg'],
  ['Fermat’s Enigma', 'Simon Singh'],
  ['The Joy of x', 'Steven Strogatz'],
  ['Flatland', 'Edwin Abbott'],
  ['Mathematics for the IB Diploma', 'Paul Fannon'],
  ['Physics for the IB Diploma', 'K. A. Tsokos'],
  ['Chemistry for the IB Diploma', 'Steve Owen'],
  ['Biology for the IB Diploma', 'Brenda Walpole'],
  ['English Language and Literature', 'Brad Philpot'],
  ['Economics for the IB Diploma', 'Ellie Tragakes'],
];
export function seed(): Entry[] {
  const out: Entry[] = [];
  const add = (kind: string, name: string, data: any, quantity = 0) => {
    const r = {
      id: kind + '-' + (out.filter((x) => x.kind === kind).length + 1),
      kind,
      name,
      data,
      quantity,
    };
    out.push(r);
    return r;
  };
  [chem, physics, bio].forEach((items, l) =>
    items.forEach((name, i) =>
      add(
        'inventory',
        name,
        {
          lab: ['Chemistry', 'Physics', 'Biology'][l],
          category:
            l === 0
              ? i < 6 || i === 18
                ? 'Chemicals'
                : i < 13
                  ? 'Glassware'
                  : i > 14 && i < 18
                    ? 'Safety'
                    : 'General'
              : l === 1
                ? i < 6
                  ? 'Electrical'
                  : i < 10
                    ? 'Mechanics'
                    : i < 14
                      ? 'Optics'
                      : 'Measurement'
                : i < 4
                  ? 'Microscopy'
                  : i < 8
                    ? 'Dissection'
                    : i < 12
                      ? 'Specimens'
                      : 'General',
          unit: l === 0 && i < 6 ? 'mL' : 'pcs',
          minimumQuantity: i % 6 === 0 ? 10 : 3,
          location: `${['C', 'P', 'B'][l]}${(i % 3) + 1} · Cabinet ${Math.floor(i / 5) + 1}`,
          condition: 'Good',
          description: `For supervised ${['chemistry', 'physics', 'biology'][l].toLowerCase()} practical work. Return equipment clean and report any damage after use.`,
          safetyInformation:
            l === 0
              ? 'Wear eye protection and gloves. Follow the laboratory safety protocol.'
              : 'Use under staff supervision.',
          chemicalFormula:
            l === 0 ? ['NaCl', 'HCl', 'CuSO₄', 'C₂H₅OH', 'H₂O', 'NaOH'][i] : '',
          updatedAt: '2026-09-06',
        },
        i % 13 === 0 ? 0 : i % 7 === 0 ? 2 : l === 0 && i < 6 ? 500 : 12 + i,
      ),
    ),
  );
  titles.forEach(([name, author], i) =>
    add(
      'book',
      name,
      {
        author,
        subject:
          i < 10
            ? 'Science'
            : i < 28
              ? 'Literature'
              : i < 35
                ? 'Science'
                : i < 40
                  ? 'Economics'
                  : 'Mathematics',
        isbn: `978000${String(i + 1000).padStart(6, '0')}`,
        publicationYear: 2000 + (i % 24),
        language: 'English',
        publisher: 'School library collection',
        description: `Explore ${name} by ${author}. Available through the Westbridge school library for independent reading and classroom study.`,
        location: `Library · Shelf ${String.fromCharCode(65 + (i % 6))}`,
        total: 3,
      },
      i % 8 === 0 ? 0 : i >= 1 && i <= 8 ? 2 : 3,
    ),
  );
  // 30 Detailed Student Profiles with Complete Fake Data
  const studentProfiles = [
    {
      name: 'Nithin Selvaraj',
      studentId: 'WB26001',
      admissionNumber: 'ADM-2024-1001',
      grade: 'DP-2',
      homeroom: 'DP-2',
      house: 'Phoenix',
      homeroomTeacher: 'Sadahana',
      homeroomTeacherEmail: 'teacher.dev@schoolos.local',
      homeroomTeacherPhone: '+91 98400 12001',
      counselor: 'Dr. Aisha Rahman',
      lockerNumber: 'L-204',
      dateOfBirth: '2008-04-12',
      gender: 'Male',
      bloodGroup: 'O+',
      nationality: 'Indian',
      studentEmail: 'nithin.selvaraj@student.westbridge.edu',
      studentPhone: '+91 98401 55201',
      address: 'Apartment 402, Marina Bay Towers, 14 Santhome High Road, Mylapore, Chennai, Tamil Nadu - 600004',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600004',
      primaryParentName: 'Rajesh Selvaraj',
      primaryParentRelation: 'Father',
      primaryParentPhone: '+91 98840 71101',
      primaryParentEmail: 'rajesh.selvaraj@techcorp.com',
      primaryParentOccupation: 'VP of Software Engineering',
      primaryParentCompany: 'Cognizant Technologies',
      secondaryParentName: 'Ananya Selvaraj',
      secondaryParentRelation: 'Mother',
      secondaryParentPhone: '+91 98840 82201',
      secondaryParentEmail: 'ananya.selvaraj@cfoadvisors.in',
      secondaryParentOccupation: 'Chief Financial Officer',
      secondaryParentCompany: 'Apex Financial Services',
      emergencyContactName: 'Rajesh Selvaraj',
      emergencyContactRelation: 'Father',
      emergencyContactPhone: '+91 98840 71101',
      emergencyContactEmail: 'rajesh.selvaraj@techcorp.com',
      transportMode: 'School Bus #12 (Route 4 - Mylapore to Adyar)',
      busRoute: 'Route 4 - Mylapore to Adyar',
      busStop: 'Santhome Church Bus Bay',
      medicalNotes: 'No chronic medical conditions · Fully cleared for all IB DP sports & lab sessions',
      allergies: 'None',
      dietaryPreference: 'Vegetarian',
      attendance: 98,
      average: 94,
      gpa: '4.00 / 4.00',
      predictedScore: '43 / 45 (IBDP)',
      extendedEssayTopic: 'Computational modeling of plasma magnetic confinement in tokamak reactors',
      casHours: 165,
    },
    {
      name: 'Emma Wilson',
      studentId: 'WB26002',
      admissionNumber: 'ADM-2024-1002',
      grade: 'DP-2',
      homeroom: 'DP-2',
      house: 'Pegasus',
      homeroomTeacher: 'Sadahana',
      homeroomTeacherEmail: 'teacher.dev@schoolos.local',
      homeroomTeacherPhone: '+91 98400 12001',
      counselor: 'Dr. Aisha Rahman',
      lockerNumber: 'L-205',
      dateOfBirth: '2008-06-18',
      gender: 'Female',
      bloodGroup: 'A+',
      nationality: 'British',
      studentEmail: 'emma.wilson@student.westbridge.edu',
      studentPhone: '+91 98401 55202',
      address: 'Villa 12, Palm Meadows Enclave, Boat Club Road, RA Puram, Chennai, Tamil Nadu - 600028',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600028',
      primaryParentName: 'Dr. David Wilson',
      primaryParentRelation: 'Father',
      primaryParentPhone: '+91 98840 71102',
      primaryParentEmail: 'david.wilson@apollohospitals.com',
      primaryParentOccupation: 'Consultant Neurosurgeon',
      primaryParentCompany: 'Apollo Hospitals',
      secondaryParentName: 'Prof. Sarah Wilson',
      secondaryParentRelation: 'Mother',
      secondaryParentPhone: '+91 98840 82202',
      secondaryParentEmail: 'sarah.wilson@iitm.ac.in',
      secondaryParentOccupation: 'Professor of Biochemistry',
      secondaryParentCompany: 'IIT Madras',
      emergencyContactName: 'Dr. David Wilson',
      emergencyContactRelation: 'Father',
      emergencyContactPhone: '+91 98840 71102',
      emergencyContactEmail: 'david.wilson@apollohospitals.com',
      transportMode: 'Private Car / Parent Drop',
      busRoute: 'Self / Private Drop-off',
      busStop: 'Westbridge North Gate',
      medicalNotes: 'Mild Seasonal Pollen Asthma · Inhaler stored in Student Backpack and Infirmary',
      allergies: 'Tree Pollen',
      dietaryPreference: 'Non-Vegetarian',
      attendance: 96,
      average: 91,
      gpa: '3.92 / 4.00',
      predictedScore: '41 / 45 (IBDP)',
      extendedEssayTopic: 'Enzymatic hydrolysis rates of cellulose in second-generation biofuel synthesis',
      casHours: 142,
    },
    {
      name: 'Liam Chen',
      studentId: 'WB26003',
      admissionNumber: 'ADM-2024-1003',
      grade: 'DP-2',
      homeroom: 'DP-2',
      house: 'Hydra',
      homeroomTeacher: 'Sadahana',
      homeroomTeacherEmail: 'teacher.dev@schoolos.local',
      homeroomTeacherPhone: '+91 98400 12001',
      counselor: 'Dr. Aisha Rahman',
      lockerNumber: 'L-206',
      dateOfBirth: '2008-02-24',
      gender: 'Male',
      bloodGroup: 'B+',
      nationality: 'Singaporean',
      studentEmail: 'liam.chen@student.westbridge.edu',
      studentPhone: '+91 98401 55203',
      address: 'Penthouse 18A, Orchid Crest, Cenotaph Road, Teynampet, Chennai, Tamil Nadu - 600018',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600018',
      primaryParentName: 'Wei Chen',
      primaryParentRelation: 'Father',
      primaryParentPhone: '+91 98840 71103',
      primaryParentEmail: 'wei.chen@horizoncap.sg',
      primaryParentOccupation: 'Managing Partner',
      primaryParentCompany: 'Horizon Venture Capital',
      secondaryParentName: 'Mei Chen',
      secondaryParentRelation: 'Mother',
      secondaryParentPhone: '+91 98840 82203',
      secondaryParentEmail: 'mei.chen@fintechsol.com',
      secondaryParentOccupation: 'Principal Data Architect',
      secondaryParentCompany: 'FinTech Solutions Global',
      emergencyContactName: 'Mei Chen',
      emergencyContactRelation: 'Mother',
      emergencyContactPhone: '+91 98840 82203',
      emergencyContactEmail: 'mei.chen@fintechsol.com',
      transportMode: 'School Bus #08 (Route 7 - Teynampet to Adyar)',
      busRoute: 'Route 7 - Teynampet to Adyar',
      busStop: 'Cenotaph Road Junction',
      medicalNotes: 'No chronic conditions · Wears corrective lenses for computer work',
      allergies: 'None',
      dietaryPreference: 'Non-Vegetarian',
      attendance: 95,
      average: 89,
      gpa: '3.88 / 4.00',
      predictedScore: '40 / 45 (IBDP)',
      extendedEssayTopic: 'Consensus latency and fault-tolerance tradeoffs in asynchronous Byzantine agreement protocols',
      casHours: 155,
    },
    {
      name: 'Sofia Martinez',
      studentId: 'WB26004',
      admissionNumber: 'ADM-2024-1004',
      grade: 'DP-2',
      homeroom: 'DP-2',
      house: 'Orion',
      homeroomTeacher: 'Sadahana',
      homeroomTeacherEmail: 'teacher.dev@schoolos.local',
      homeroomTeacherPhone: '+91 98400 12001',
      counselor: 'Dr. Aisha Rahman',
      lockerNumber: 'L-207',
      dateOfBirth: '2008-09-05',
      gender: 'Female',
      bloodGroup: 'O-',
      nationality: 'Spanish',
      studentEmail: 'sofia.martinez@student.westbridge.edu',
      studentPhone: '+91 98401 55204',
      address: 'Bungalow 7, Olive Gardens, Poes Garden, Chennai, Tamil Nadu - 600086',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600086',
      primaryParentName: 'Carlos Martinez',
      primaryParentRelation: 'Father',
      primaryParentPhone: '+91 98840 71104',
      primaryParentEmail: 'carlos.martinez@studiomartinez.es',
      primaryParentOccupation: 'Principal Architect & Urban Designer',
      primaryParentCompany: 'Studio Martinez Architecture',
      secondaryParentName: 'Elena Martinez',
      secondaryParentRelation: 'Mother',
      secondaryParentPhone: '+91 98840 82204',
      secondaryParentEmail: 'elena.martinez@unesco.org',
      secondaryParentOccupation: 'Senior Cultural Heritage Officer',
      secondaryParentCompany: 'UNESCO Regional Mission',
      emergencyContactName: 'Carlos Martinez',
      emergencyContactRelation: 'Father',
      emergencyContactPhone: '+91 98840 71104',
      emergencyContactEmail: 'carlos.martinez@studiomartinez.es',
      transportMode: 'Private Car / Parent Drop',
      busRoute: 'Self / Private Drop-off',
      busStop: 'Westbridge Main Porch',
      medicalNotes: 'Severe Peanut & Tree Nut Allergy · Twin EpiPens kept with Homeroom Teacher and Infirmary',
      allergies: 'Peanuts, Cashews, Walnuts',
      dietaryPreference: 'Vegetarian',
      attendance: 97,
      average: 93,
      gpa: '3.96 / 4.00',
      predictedScore: '42 / 45 (IBDP)',
      extendedEssayTopic: 'Magical realism as resistance against authoritarianism in Gabriel García Márquez and Isabel Allende',
      casHours: 170,
    },
    {
      name: 'Noah Patel',
      studentId: 'WB26005',
      admissionNumber: 'ADM-2024-1005',
      grade: 'DP-2',
      homeroom: 'DP-2',
      house: 'Aquila',
      homeroomTeacher: 'Sadahana',
      homeroomTeacherEmail: 'teacher.dev@schoolos.local',
      homeroomTeacherPhone: '+91 98400 12001',
      counselor: 'Dr. Aisha Rahman',
      lockerNumber: 'L-208',
      dateOfBirth: '2008-11-30',
      gender: 'Male',
      bloodGroup: 'AB+',
      nationality: 'Indian',
      studentEmail: 'noah.patel@student.westbridge.edu',
      studentPhone: '+91 98401 55205',
      address: 'Block C, Flat 901, Green Meadows Heights, 2nd Main Road, Gandhi Nagar, Adyar, Chennai - 600020',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600020',
      primaryParentName: 'Ramesh Patel',
      primaryParentRelation: 'Father',
      primaryParentPhone: '+91 98840 71105',
      primaryParentEmail: 'ramesh.patel@apexinfra.in',
      primaryParentOccupation: 'Managing Director',
      primaryParentCompany: 'Apex Infrastructure Group',
      secondaryParentName: 'Pooja Patel',
      secondaryParentRelation: 'Mother',
      secondaryParentPhone: '+91 98840 82205',
      secondaryParentEmail: 'pooja.patel@mindwellness.in',
      secondaryParentOccupation: 'Senior Clinical Psychologist',
      secondaryParentCompany: 'Mind Wellness Clinic',
      emergencyContactName: 'Pooja Patel',
      emergencyContactRelation: 'Mother',
      emergencyContactPhone: '+91 98840 82205',
      emergencyContactEmail: 'pooja.patel@mindwellness.in',
      transportMode: 'School Bus #12 (Route 4 - Mylapore to Adyar)',
      busRoute: 'Route 4 - Mylapore to Adyar',
      busStop: 'Gandhi Nagar Bus Stop',
      medicalNotes: 'No medical conditions · Fully cleared for athletics',
      allergies: 'None',
      dietaryPreference: 'Vegetarian',
      attendance: 94,
      average: 88,
      gpa: '3.82 / 4.00',
      predictedScore: '39 / 45 (IBDP)',
      extendedEssayTopic: 'Graph-theoretic heuristics for multi-depot vehicle routing in congested metropolitan networks',
      casHours: 138,
    },
    {
      name: 'Isabella Brown',
      studentId: 'WB26006',
      admissionNumber: 'ADM-2024-1006',
      grade: 'DP-2',
      homeroom: 'DP-2',
      house: 'Centaurus',
      homeroomTeacher: 'Sadahana',
      homeroomTeacherEmail: 'teacher.dev@schoolos.local',
      homeroomTeacherPhone: '+91 98400 12001',
      counselor: 'Dr. Aisha Rahman',
      lockerNumber: 'L-209',
      dateOfBirth: '2008-01-14',
      gender: 'Female',
      bloodGroup: 'A-',
      nationality: 'American',
      studentEmail: 'isabella.brown@student.westbridge.edu',
      studentPhone: '+91 98401 55206',
      address: 'House 5A, Silver Oak Enclave, Kalakshetra Colony, Besant Nagar, Chennai, Tamil Nadu - 600090',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600090',
      primaryParentName: 'Robert Brown',
      primaryParentRelation: 'Father',
      primaryParentPhone: '+91 98840 71106',
      primaryParentEmail: 'robert.brown@earthwatch.org',
      primaryParentOccupation: 'Marine Environmental Scientist',
      primaryParentCompany: 'Earthwatch Oceanic Institute',
      secondaryParentName: 'Jennifer Brown',
      secondaryParentRelation: 'Mother',
      secondaryParentPhone: '+91 98840 82206',
      secondaryParentEmail: 'jennifer.brown@usconsulate.gov',
      secondaryParentOccupation: 'Commercial Diplomat',
      secondaryParentCompany: 'US Consulate General',
      emergencyContactName: 'Robert Brown',
      emergencyContactRelation: 'Father',
      emergencyContactPhone: '+91 98840 71106',
      emergencyContactEmail: 'robert.brown@earthwatch.org',
      transportMode: 'Bicycle / Green Commute',
      busRoute: 'Self / Bicycle Route',
      busStop: 'Westbridge Bike Rack Zone',
      medicalNotes: 'Lactose Intolerant · Requires dairy-free cafeteria options',
      allergies: 'Dairy / Lactose',
      dietaryPreference: 'Vegetarian',
      attendance: 99,
      average: 96,
      gpa: '4.00 / 4.00',
      predictedScore: '44 / 45 (IBDP)',
      extendedEssayTopic: 'FTIR spectroscopic characterization of microplastic polymer degradation in coastal estuarine zones',
      casHours: 190,
    },
    {
      name: 'Oliver Kim',
      studentId: 'WB26007',
      admissionNumber: 'ADM-2025-1007',
      grade: 'Grade 11',
      homeroom: '11A',
      house: 'Phoenix',
      homeroomTeacher: 'Ms. Shalaba',
      homeroomTeacherEmail: 'msshalaba@westbridge.edu',
      homeroomTeacherPhone: '+91 98400 22002',
      counselor: 'Dr. Aisha Rahman',
      lockerNumber: 'L-112',
      dateOfBirth: '2009-05-22',
      gender: 'Male',
      bloodGroup: 'O+',
      nationality: 'Korean',
      studentEmail: 'oliver.kim@student.westbridge.edu',
      studentPhone: '+91 98401 55207',
      address: 'Flat 11B, Sky High Residencies, 4th Seaward Road, Valmiki Nagar, Thiruvanmiyur, Chennai - 600041',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600041',
      primaryParentName: 'Min-jun Kim',
      primaryParentRelation: 'Father',
      primaryParentPhone: '+91 98840 71107',
      primaryParentEmail: 'minjun.kim@hyundaimotors.com',
      primaryParentOccupation: 'Executive Director of R&D',
      primaryParentCompany: 'Hyundai Motor India',
      secondaryParentName: 'Sun-hee Kim',
      secondaryParentRelation: 'Mother',
      secondaryParentPhone: '+91 98840 82207',
      secondaryParentEmail: 'sunhee.kim@koreancenter.org',
      secondaryParentOccupation: 'Director of Cultural Exchange',
      secondaryParentCompany: 'Korea Foundation',
      emergencyContactName: 'Min-jun Kim',
      emergencyContactRelation: 'Father',
      emergencyContactPhone: '+91 98840 71107',
      emergencyContactEmail: 'minjun.kim@hyundaimotors.com',
      transportMode: 'School Bus #15 (Route 9 - Thiruvanmiyur)',
      busRoute: 'Route 9 - Thiruvanmiyur',
      busStop: 'Valmiki Nagar Bus Stop',
      medicalNotes: 'No known medical conditions',
      allergies: 'None',
      dietaryPreference: 'Non-Vegetarian',
      attendance: 95,
      average: 90,
      gpa: '3.90 / 4.00',
      predictedScore: '40 / 45 (IBDP)',
      extendedEssayTopic: 'Cross-price elasticity of electric vehicles under varying national subsidy frameworks',
      casHours: 95,
    },
    {
      name: 'Mia Thompson',
      studentId: 'WB26008',
      admissionNumber: 'ADM-2025-1008',
      grade: 'Grade 11',
      homeroom: '11A',
      house: 'Pegasus',
      homeroomTeacher: 'Ms. Shalaba',
      homeroomTeacherEmail: 'msshalaba@westbridge.edu',
      homeroomTeacherPhone: '+91 98400 22002',
      counselor: 'Dr. Aisha Rahman',
      lockerNumber: 'L-113',
      dateOfBirth: '2009-08-11',
      gender: 'Female',
      bloodGroup: 'B+',
      nationality: 'Australian',
      studentEmail: 'mia.thompson@student.westbridge.edu',
      studentPhone: '+91 98401 55208',
      address: 'Villa 22, Whispering Palms, Kottur Gardens, Kotturpuram, Chennai, Tamil Nadu - 600085',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600085',
      primaryParentName: 'Paul Thompson',
      primaryParentRelation: 'Father',
      primaryParentPhone: '+91 98840 71108',
      primaryParentEmail: 'paul.thompson@bhp.com',
      primaryParentOccupation: 'Chief Geoscientist',
      primaryParentCompany: 'BHP Minerals International',
      secondaryParentName: 'Rachel Thompson',
      secondaryParentRelation: 'Mother',
      secondaryParentPhone: '+91 98840 82208',
      secondaryParentEmail: 'rachel.thompson@reuters.com',
      secondaryParentOccupation: 'Senior South Asia Correspondent',
      secondaryParentCompany: 'Thomson Reuters',
      emergencyContactName: 'Rachel Thompson',
      emergencyContactRelation: 'Mother',
      emergencyContactPhone: '+91 98840 82208',
      emergencyContactEmail: 'rachel.thompson@reuters.com',
      transportMode: 'School Bus #08 (Route 7 - Kotturpuram to Adyar)',
      busRoute: 'Route 7 - Kotturpuram to Adyar',
      busStop: 'Kotturpuram Railway Station Gate',
      medicalNotes: 'Mild Eczema · Hypoallergenic soaps requested in science laboratories',
      allergies: 'Latex Gloves (requires Nitrile)',
      dietaryPreference: 'Vegetarian',
      attendance: 97,
      average: 92,
      gpa: '3.94 / 4.00',
      predictedScore: '41 / 45 (IBDP)',
      extendedEssayTopic: 'CRISPR-Cas9 on-target cleavage efficiency in drought-resistant Oryza sativa cultivars',
      casHours: 110,
    },
    {
      name: 'Ethan Davis',
      studentId: 'WB26009',
      admissionNumber: 'ADM-2025-1009',
      grade: 'Grade 11',
      homeroom: '11A',
      house: 'Hydra',
      homeroomTeacher: 'Ms. Shalaba',
      homeroomTeacherEmail: 'msshalaba@westbridge.edu',
      homeroomTeacherPhone: '+91 98400 22002',
      counselor: 'Dr. Aisha Rahman',
      lockerNumber: 'L-114',
      dateOfBirth: '2009-03-15',
      gender: 'Male',
      bloodGroup: 'AB-',
      nationality: 'Canadian',
      studentEmail: 'ethan.davis@student.westbridge.edu',
      studentPhone: '+91 98401 55209',
      address: 'Flat 5C, Harrington Court, Harrington Road, Chetpet, Chennai, Tamil Nadu - 600031',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600031',
      primaryParentName: 'Thomas Davis',
      primaryParentRelation: 'Father',
      primaryParentPhone: '+91 98840 71109',
      primaryParentEmail: 'thomas.davis@bombardier.ca',
      primaryParentOccupation: 'Aerospace Flight Controls Engineer',
      primaryParentCompany: 'Bombardier Aerospace',
      secondaryParentName: 'Dr. Laura Davis',
      secondaryParentRelation: 'Mother',
      secondaryParentPhone: '+91 98840 82209',
      secondaryParentEmail: 'laura.davis@srmmedical.edu',
      secondaryParentOccupation: 'Professor of Surgery',
      secondaryParentCompany: 'SRM Medical College & Research Center',
      emergencyContactName: 'Thomas Davis',
      emergencyContactRelation: 'Father',
      emergencyContactPhone: '+91 98840 71109',
      emergencyContactEmail: 'thomas.davis@bombardier.ca',
      transportMode: 'School Bus #19 (Route 3 - Chetpet & Nungambakkam)',
      busRoute: 'Route 3 - Chetpet & Nungambakkam',
      busStop: 'Harrington Road Junction',
      medicalNotes: 'No medical conditions · Cleared for competitive swimming and football',
      allergies: 'None',
      dietaryPreference: 'Non-Vegetarian',
      attendance: 93,
      average: 86,
      gpa: '3.75 / 4.00',
      predictedScore: '38 / 45 (IBDP)',
      extendedEssayTopic: 'Decoherence suppression mechanisms in superconducting transmon qubit architectures',
      casHours: 88,
    },
    {
      name: 'Amelia Singh',
      studentId: 'WB26010',
      admissionNumber: 'ADM-2025-1010',
      grade: 'Grade 11',
      homeroom: '11A',
      house: 'Orion',
      homeroomTeacher: 'Ms. Shalaba',
      homeroomTeacherEmail: 'msshalaba@westbridge.edu',
      homeroomTeacherPhone: '+91 98400 22002',
      counselor: 'Dr. Aisha Rahman',
      lockerNumber: 'L-115',
      dateOfBirth: '2009-10-08',
      gender: 'Female',
      bloodGroup: 'O+',
      nationality: 'Indian',
      studentEmail: 'amelia.singh@student.westbridge.edu',
      studentPhone: '+91 98401 55210',
      address: 'House 88, Chamiers Road, Nandanam Extension, Chennai, Tamil Nadu - 600035',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600035',
      primaryParentName: 'Gurpreet Singh',
      primaryParentRelation: 'Father',
      primaryParentPhone: '+91 98840 71110',
      primaryParentEmail: 'gurpreet.singh@sc.com',
      primaryParentOccupation: 'Senior Vice President of Wealth Management',
      primaryParentCompany: 'Standard Chartered Bank',
      secondaryParentName: 'Simran Singh',
      secondaryParentRelation: 'Mother',
      secondaryParentPhone: '+91 98840 82210',
      secondaryParentEmail: 'simran.singh@singhdesign.in',
      secondaryParentOccupation: 'Lead Interior Architecture Consultant',
      secondaryParentCompany: 'Studio Singh Interiors',
      emergencyContactName: 'Gurpreet Singh',
      emergencyContactRelation: 'Father',
      emergencyContactPhone: '+91 98840 71110',
      emergencyContactEmail: 'gurpreet.singh@sc.com',
      transportMode: 'School Bus #08 (Route 7 - Nandanam)',
      busRoute: 'Route 7 - Nandanam',
      busStop: 'Chamiers Road Signal',
      medicalNotes: 'No chronic conditions',
      allergies: 'None',
      dietaryPreference: 'Vegetarian',
      attendance: 98,
      average: 95,
      gpa: '4.00 / 4.00',
      predictedScore: '43 / 45 (IBDP)',
      extendedEssayTopic: 'Nudge theory applications in mobile micro-savings engagement among low-income households',
      casHours: 125,
    },
    {
      name: 'Lucas Garcia',
      studentId: 'WB26011',
      admissionNumber: 'ADM-2025-1011',
      grade: 'Grade 11',
      homeroom: '11A',
      house: 'Aquila',
      homeroomTeacher: 'Ms. Shalaba',
      homeroomTeacherEmail: 'msshalaba@westbridge.edu',
      homeroomTeacherPhone: '+91 98400 22002',
      counselor: 'Dr. Aisha Rahman',
      lockerNumber: 'L-116',
      dateOfBirth: '2009-07-03',
      gender: 'Male',
      bloodGroup: 'A+',
      nationality: 'Mexican',
      studentEmail: 'lucas.garcia@student.westbridge.edu',
      studentPhone: '+91 98401 55211',
      address: 'Apartment 304, Green Park Manor, Ormes Road, Kilpauk, Chennai - 600010',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600010',
      primaryParentName: 'Mateo Garcia',
      primaryParentRelation: 'Father',
      primaryParentPhone: '+91 98840 71111',
      primaryParentEmail: 'mateo.garcia@cemex.com',
      primaryParentOccupation: 'Regional Engineering Director',
      primaryParentCompany: 'CEMEX Infrastructure',
      secondaryParentName: 'Isabella Garcia',
      secondaryParentRelation: 'Mother',
      secondaryParentPhone: '+91 98840 82211',
      secondaryParentEmail: 'isabella.garcia@biocorp.com',
      secondaryParentOccupation: 'Principal Clinical Microbiologist',
      secondaryParentCompany: 'BioCorp Laboratories',
      emergencyContactName: 'Mateo Garcia',
      emergencyContactRelation: 'Father',
      emergencyContactPhone: '+91 98840 71111',
      emergencyContactEmail: 'mateo.garcia@cemex.com',
      transportMode: 'School Bus #19 (Route 3 - Kilpauk)',
      busRoute: 'Route 3 - Kilpauk',
      busStop: 'Kilpauk Water Works Stop',
      medicalNotes: 'Mild Asthma · Cleared for physical PE activities',
      allergies: 'Dust Mites',
      dietaryPreference: 'Non-Vegetarian',
      attendance: 94,
      average: 87,
      gpa: '3.78 / 4.00',
      predictedScore: '38 / 45 (IBDP)',
      extendedEssayTopic: 'Carrier diffusion length enhancement in triple-cation perovskite solar cells',
      casHours: 85,
    },
    {
      name: 'Charlotte Lee',
      studentId: 'WB26012',
      admissionNumber: 'ADM-2025-1012',
      grade: 'Grade 11',
      homeroom: '11A',
      house: 'Centaurus',
      homeroomTeacher: 'Ms. Shalaba',
      homeroomTeacherEmail: 'msshalaba@westbridge.edu',
      homeroomTeacherPhone: '+91 98400 22002',
      counselor: 'Dr. Aisha Rahman',
      lockerNumber: 'L-117',
      dateOfBirth: '2009-12-19',
      gender: 'Female',
      bloodGroup: 'B-',
      nationality: 'Singaporean',
      studentEmail: 'charlotte.lee@student.westbridge.edu',
      studentPhone: '+91 98401 55212',
      address: 'Villa 14, Whispering Woods, Kasturi Ranga Road, Alwarpet, Chennai - 600018',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600018',
      primaryParentName: 'Jun-ho Lee',
      primaryParentRelation: 'Father',
      primaryParentPhone: '+91 98840 71112',
      primaryParentEmail: 'junho.lee@deepmind.com',
      primaryParentOccupation: 'Director of AI Research',
      primaryParentCompany: 'DeepMind Research',
      secondaryParentName: 'Dr. Grace Lee',
      secondaryParentRelation: 'Mother',
      secondaryParentPhone: '+91 98840 82212',
      secondaryParentEmail: 'grace.lee@kauveryhospital.com',
      secondaryParentOccupation: 'Senior Neurologist',
      secondaryParentCompany: 'Kauvery Hospital',
      emergencyContactName: 'Dr. Grace Lee',
      emergencyContactRelation: 'Mother',
      emergencyContactPhone: '+91 98840 82212',
      emergencyContactEmail: 'grace.lee@kauveryhospital.com',
      transportMode: 'School Bus #08 (Route 7 - Alwarpet)',
      busRoute: 'Route 7 - Alwarpet',
      busStop: 'Kasturi Ranga Road Corner',
      medicalNotes: 'No chronic conditions · Excellent physical endurance',
      allergies: 'None',
      dietaryPreference: 'Vegetarian',
      attendance: 98,
      average: 97,
      gpa: '4.00 / 4.00',
      predictedScore: '44 / 45 (IBDP)',
      extendedEssayTopic: 'Transformer-based multi-lead ECG rhythm classification with temporal self-attention',
      casHours: 130,
    },
    {
      name: 'Mason Anderson',
      studentId: 'WB26013',
      admissionNumber: 'ADM-2025-1013',
      grade: 'Grade 11',
      homeroom: '11A',
      house: 'Phoenix',
      homeroomTeacher: 'Dr. Mallu',
      homeroomTeacherEmail: 'drmallu@westbridge.edu',
      homeroomTeacherPhone: '+91 98400 22003',
      counselor: 'Dr. Aisha Rahman',
      lockerNumber: 'L-118',
      dateOfBirth: '2009-04-09',
      gender: 'Male',
      bloodGroup: 'O+',
      nationality: 'New Zealander',
      studentEmail: 'mason.anderson@student.westbridge.edu',
      studentPhone: '+91 98401 55213',
      address: 'House 3, Palm Avenue, 1st Cross Street, Karpagam Gardens, Adyar, Chennai - 600020',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600020',
      primaryParentName: 'Jonathan Anderson',
      primaryParentRelation: 'Father',
      primaryParentPhone: '+91 98840 71113',
      primaryParentEmail: 'jonathan.anderson@kpmg.com',
      primaryParentOccupation: 'Partner - Forensic Advisory',
      primaryParentCompany: 'KPMG Advisory',
      secondaryParentName: 'Claire Anderson',
      secondaryParentRelation: 'Mother',
      secondaryParentPhone: '+91 98840 82213',
      secondaryParentEmail: 'claire.anderson@pfizer.com',
      secondaryParentOccupation: 'Director of Regulatory Affairs',
      secondaryParentCompany: 'Pfizer Global Health',
      emergencyContactName: 'Jonathan Anderson',
      emergencyContactRelation: 'Father',
      emergencyContactPhone: '+91 98840 71113',
      emergencyContactEmail: 'jonathan.anderson@kpmg.com',
      transportMode: 'Bicycle / Green Commute',
      busRoute: 'Self / Bicycle Route',
      busStop: 'Westbridge Bike Station',
      medicalNotes: 'No medical conditions',
      allergies: 'None',
      dietaryPreference: 'Non-Vegetarian',
      attendance: 96,
      average: 89,
      gpa: '3.85 / 4.00',
      predictedScore: '39 / 45 (IBDP)',
      extendedEssayTopic: 'Exergy destruction in proton-exchange membrane fuel cell stacks under variable load cycles',
      casHours: 92,
    },
    {
      name: 'Harper Clark',
      studentId: 'WB26014',
      admissionNumber: 'ADM-2025-1014',
      grade: 'Grade 11',
      homeroom: '11A',
      house: 'Pegasus',
      homeroomTeacher: 'Dr. Mallu',
      homeroomTeacherEmail: 'drmallu@westbridge.edu',
      homeroomTeacherPhone: '+91 98400 22003',
      counselor: 'Dr. Aisha Rahman',
      lockerNumber: 'L-119',
      dateOfBirth: '2009-11-27',
      gender: 'Female',
      bloodGroup: 'A+',
      nationality: 'British',
      studentEmail: 'harper.clark@student.westbridge.edu',
      studentPhone: '+91 98401 55214',
      address: 'Flat 4A, Royal Palms, Sterling Road, Nungambakkam, Chennai, Tamil Nadu - 600034',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600034',
      primaryParentName: 'Prof. Richard Clark',
      primaryParentRelation: 'Father',
      primaryParentPhone: '+91 98840 71114',
      primaryParentEmail: 'richard.clark@ox.ac.uk',
      primaryParentOccupation: 'Visiting Professor of Cognitive Linguistics',
      primaryParentCompany: 'University of Oxford / IITM',
      secondaryParentName: 'Victoria Clark',
      secondaryParentRelation: 'Mother',
      secondaryParentPhone: '+91 98840 82214',
      secondaryParentEmail: 'victoria.clark@mckinsey.com',
      secondaryParentOccupation: 'Senior Partner - Education Practice',
      secondaryParentCompany: 'McKinsey & Company',
      emergencyContactName: 'Victoria Clark',
      emergencyContactRelation: 'Mother',
      emergencyContactPhone: '+91 98840 82214',
      emergencyContactEmail: 'victoria.clark@mckinsey.com',
      transportMode: 'School Bus #19 (Route 3 - Nungambakkam)',
      busRoute: 'Route 3 - Nungambakkam',
      busStop: 'Sterling Road Signal',
      medicalNotes: 'Wears corrective glasses · No other conditions',
      allergies: 'None',
      dietaryPreference: 'Vegetarian',
      attendance: 97,
      average: 94,
      gpa: '3.98 / 4.00',
      predictedScore: '42 / 45 (IBDP)',
      extendedEssayTopic: 'Neural correlates of executive function advantages in simultaneous early bilingualism',
      casHours: 115,
    },
    {
      name: 'Logan Robinson',
      studentId: 'WB26015',
      admissionNumber: 'ADM-2025-1015',
      grade: 'Grade 11',
      homeroom: '11A',
      house: 'Hydra',
      homeroomTeacher: 'Dr. Mallu',
      homeroomTeacherEmail: 'drmallu@westbridge.edu',
      homeroomTeacherPhone: '+91 98400 22003',
      counselor: 'Dr. Aisha Rahman',
      lockerNumber: 'L-120',
      dateOfBirth: '2009-01-31',
      gender: 'Male',
      bloodGroup: 'O-',
      nationality: 'South African',
      studentEmail: 'logan.robinson@student.westbridge.edu',
      studentPhone: '+91 98401 55215',
      address: 'Villa 19, Emerald Bay Estate, ECR Main Road, Palavakkam, Chennai - 600041',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600041',
      primaryParentName: 'Kevin Robinson',
      primaryParentRelation: 'Father',
      primaryParentPhone: '+91 98840 71115',
      primaryParentEmail: 'kevin.robinson@angloamerican.com',
      primaryParentOccupation: 'VP of Mining Operations',
      primaryParentCompany: 'Anglo American South Asia',
      secondaryParentName: 'Samantha Robinson',
      secondaryParentRelation: 'Mother',
      secondaryParentPhone: '+91 98840 82215',
      secondaryParentEmail: 'samantha.robinson@uct.ac.za',
      secondaryParentOccupation: 'Dean of Humanities',
      secondaryParentCompany: 'Cape Town University / Global Academy',
      emergencyContactName: 'Kevin Robinson',
      emergencyContactRelation: 'Father',
      emergencyContactPhone: '+91 98840 71115',
      emergencyContactEmail: 'kevin.robinson@angloamerican.com',
      transportMode: 'School Bus #22 (Route 11 - ECR & Palavakkam)',
      busRoute: 'Route 11 - ECR & Palavakkam',
      busStop: 'Palavakkam Bus Depot',
      medicalNotes: 'No medical conditions · Team Captain for School Rugby',
      allergies: 'None',
      dietaryPreference: 'Non-Vegetarian',
      attendance: 94,
      average: 88,
      gpa: '3.80 / 4.00',
      predictedScore: '39 / 45 (IBDP)',
      extendedEssayTopic: 'Supercontinuum spectral generation dynamics in dispersion-engineered photonic crystal fibers',
      casHours: 105,
    },
    {
      name: 'Evelyn Lewis',
      studentId: 'WB26016',
      admissionNumber: 'ADM-2024-1016',
      grade: 'Grade 12',
      homeroom: '12B',
      house: 'Orion',
      homeroomTeacher: 'Mr. Rishikesh',
      homeroomTeacherEmail: 'mrrishikesh@westbridge.edu',
      homeroomTeacherPhone: '+91 98400 22004',
      counselor: 'Dr. Aisha Rahman',
      lockerNumber: 'L-221',
      dateOfBirth: '2008-07-25',
      gender: 'Female',
      bloodGroup: 'B+',
      nationality: 'Canadian',
      studentEmail: 'evelyn.lewis@student.westbridge.edu',
      studentPhone: '+91 98401 55216',
      address: 'Apartment 7B, Chaitanya Towers, Luz Church Road, Mylapore, Chennai - 600004',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600004',
      primaryParentName: 'Steven Lewis',
      primaryParentRelation: 'Father',
      primaryParentPhone: '+91 98840 71116',
      primaryParentEmail: 'steven.lewis@deloitte.ca',
      primaryParentOccupation: 'Managing Partner - Risk Advisory',
      primaryParentCompany: 'Deloitte Canada',
      secondaryParentName: 'Dr. Rebecca Lewis',
      secondaryParentRelation: 'Mother',
      secondaryParentPhone: '+91 98840 82216',
      secondaryParentEmail: 'rebecca.lewis@sickkids.ca',
      secondaryParentOccupation: 'Pediatric Cardiologist',
      secondaryParentCompany: 'Hospital for Sick Children & MGM Healthcare',
      emergencyContactName: 'Dr. Rebecca Lewis',
      emergencyContactRelation: 'Mother',
      emergencyContactPhone: '+91 98840 82216',
      emergencyContactEmail: 'rebecca.lewis@sickkids.ca',
      transportMode: 'School Bus #12 (Route 4 - Mylapore)',
      busRoute: 'Route 4 - Mylapore',
      busStop: 'Luz Corner Stop',
      medicalNotes: 'No medical conditions',
      allergies: 'None',
      dietaryPreference: 'Vegetarian',
      attendance: 96,
      average: 93,
      gpa: '3.95 / 4.00',
      predictedScore: '42 / 45 (IBDP)',
      extendedEssayTopic: 'The subversion of maternal paradigms in Margaret Atwood and Octavia Butler speculative fiction',
      casHours: 155,
    },
    {
      name: 'Alexander Walker',
      studentId: 'WB26017',
      admissionNumber: 'ADM-2024-1017',
      grade: 'Grade 12',
      homeroom: '12B',
      house: 'Aquila',
      homeroomTeacher: 'Mr. Rishikesh',
      homeroomTeacherEmail: 'mrrishikesh@westbridge.edu',
      homeroomTeacherPhone: '+91 98400 22004',
      counselor: 'Dr. Aisha Rahman',
      lockerNumber: 'L-222',
      dateOfBirth: '2008-03-10',
      gender: 'Male',
      bloodGroup: 'A-',
      nationality: 'Australian',
      studentEmail: 'alexander.walker@student.westbridge.edu',
      studentPhone: '+91 98401 55217',
      address: 'House 11, Greenways Road Ext, Raja Annamalaipuram, Chennai, Tamil Nadu - 600028',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600028',
      primaryParentName: 'George Walker',
      primaryParentRelation: 'Father',
      primaryParentPhone: '+91 98840 71117',
      primaryParentEmail: 'george.walker@macquarie.com',
      primaryParentOccupation: 'Executive Director - Commodities Trading',
      primaryParentCompany: 'Macquarie Group',
      secondaryParentName: 'Natalie Walker',
      secondaryParentRelation: 'Mother',
      secondaryParentPhone: '+91 98840 82217',
      secondaryParentEmail: 'natalie.walker@arup.com',
      secondaryParentOccupation: 'Lead Structural Engineer',
      secondaryParentCompany: 'Arup Infrastructure Consultants',
      emergencyContactName: 'George Walker',
      emergencyContactRelation: 'Father',
      emergencyContactPhone: '+91 98840 71117',
      emergencyContactEmail: 'george.walker@macquarie.com',
      transportMode: 'Private Car / Parent Drop',
      busRoute: 'Self / Private Drop-off',
      busStop: 'Westbridge North Gate',
      medicalNotes: 'No known conditions · Head of School Debate Society',
      allergies: 'None',
      dietaryPreference: 'Non-Vegetarian',
      attendance: 97,
      average: 92,
      gpa: '3.92 / 4.00',
      predictedScore: '41 / 45 (IBDP)',
      extendedEssayTopic: 'Nonlinear coupled differential equations in stochastic modeling of multi-variant viral transmission',
      casHours: 145,
    },
    {
      name: 'Aria Hall',
      studentId: 'WB26018',
      admissionNumber: 'ADM-2024-1018',
      grade: 'Grade 12',
      homeroom: '12B',
      house: 'Centaurus',
      homeroomTeacher: 'Mr. Rishikesh',
      homeroomTeacherEmail: 'mrrishikesh@westbridge.edu',
      homeroomTeacherPhone: '+91 98400 22004',
      counselor: 'Dr. Aisha Rahman',
      lockerNumber: 'L-223',
      dateOfBirth: '2008-10-14',
      gender: 'Female',
      bloodGroup: 'AB+',
      nationality: 'British',
      studentEmail: 'aria.hall@student.westbridge.edu',
      studentPhone: '+91 98401 55218',
      address: 'Villa 6, Casuarina Bay, 5th Avenue, Besant Nagar, Chennai, Tamil Nadu - 600090',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600090',
      primaryParentName: 'Brian Hall',
      primaryParentRelation: 'Father',
      primaryParentPhone: '+91 98840 71118',
      primaryParentEmail: 'brian.hall@gsk.com',
      primaryParentOccupation: 'Director of Clinical Pharmacology',
      primaryParentCompany: 'GlaxoSmithKline Research',
      secondaryParentName: 'Katherine Hall',
      secondaryParentRelation: 'Mother',
      secondaryParentPhone: '+91 98840 82218',
      secondaryParentEmail: 'katherine.hall@zoho.com',
      secondaryParentOccupation: 'Chief Technology Officer',
      secondaryParentCompany: 'Zoho Corporation',
      emergencyContactName: 'Katherine Hall',
      emergencyContactRelation: 'Mother',
      emergencyContactPhone: '+91 98840 82218',
      emergencyContactEmail: 'katherine.hall@zoho.com',
      transportMode: 'Bicycle / Green Commute',
      busRoute: 'Self / Bicycle Route',
      busStop: 'Westbridge Bike Dock',
      medicalNotes: 'No chronic conditions · School Orchestra First Violinist',
      allergies: 'None',
      dietaryPreference: 'Vegetarian',
      attendance: 99,
      average: 98,
      gpa: '4.00 / 4.00',
      predictedScore: '45 / 45 (IBDP)',
      extendedEssayTopic: 'Electrospun crosslinked chitosan-nanocellulose hydrogel scaffolds for accelerated dermal wound regeneration',
      casHours: 180,
    },
    {
      name: 'James Allen',
      studentId: 'WB26019',
      admissionNumber: 'ADM-2024-1019',
      grade: 'Grade 12',
      homeroom: '12B',
      house: 'Phoenix',
      homeroomTeacher: 'Mr. Pramod',
      homeroomTeacherEmail: 'mrpramod@westbridge.edu',
      homeroomTeacherPhone: '+91 98400 22005',
      counselor: 'Dr. Aisha Rahman',
      lockerNumber: 'L-224',
      dateOfBirth: '2008-05-02',
      gender: 'Male',
      bloodGroup: 'O+',
      nationality: 'American',
      studentEmail: 'james.allen@student.westbridge.edu',
      studentPhone: '+91 98401 55219',
      address: 'Penthouse 14, Ceebros Boulevard, 110 Mount Road, Guindy, Chennai - 600032',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600032',
      primaryParentName: 'Christopher Allen',
      primaryParentRelation: 'Father',
      primaryParentPhone: '+91 98840 71119',
      primaryParentEmail: 'christopher.allen@bakerbotts.com',
      primaryParentOccupation: 'Senior IP & Patent Counsel',
      primaryParentCompany: 'Baker Botts LLP',
      secondaryParentName: 'Stephanie Allen',
      secondaryParentRelation: 'Mother',
      secondaryParentPhone: '+91 98840 82219',
      secondaryParentEmail: 'stephanie.allen@cern.ch',
      secondaryParentOccupation: 'Senior Particle Physicist',
      secondaryParentCompany: 'CERN Collaboration',
      emergencyContactName: 'Christopher Allen',
      emergencyContactRelation: 'Father',
      emergencyContactPhone: '+91 98840 71119',
      emergencyContactEmail: 'christopher.allen@bakerbotts.com',
      transportMode: 'School Bus #05 (Route 2 - Guindy & Saidapet)',
      busRoute: 'Route 2 - Guindy & Saidapet',
      busStop: 'Guindy Race Course Junction',
      medicalNotes: 'No medical conditions · Robotics Club President',
      allergies: 'None',
      dietaryPreference: 'Non-Vegetarian',
      attendance: 95,
      average: 91,
      gpa: '3.90 / 4.00',
      predictedScore: '41 / 45 (IBDP)',
      extendedEssayTopic: 'Experimental verification of quantum key distribution security under decoy-state BB84 protocol',
      casHours: 135,
    },
    {
      name: 'Scarlett Young',
      studentId: 'WB26020',
      admissionNumber: 'ADM-2024-1020',
      grade: 'Grade 12',
      homeroom: '12B',
      house: 'Pegasus',
      homeroomTeacher: 'Mr. Pramod',
      homeroomTeacherEmail: 'mrpramod@westbridge.edu',
      homeroomTeacherPhone: '+91 98400 22005',
      counselor: 'Dr. Aisha Rahman',
      lockerNumber: 'L-225',
      dateOfBirth: '2008-12-04',
      gender: 'Female',
      bloodGroup: 'A+',
      nationality: 'New Zealander',
      studentEmail: 'scarlett.young@student.westbridge.edu',
      studentPhone: '+91 98401 55220',
      address: 'Apartment 902, Olympus Heights, 3rd Seaward Road, Valmiki Nagar, Thiruvanmiyur, Chennai - 600041',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600041',
      primaryParentName: 'Edward Young',
      primaryParentRelation: 'Father',
      primaryParentPhone: '+91 98840 71120',
      primaryParentEmail: 'edward.young@anz.com',
      primaryParentOccupation: 'Head of Asia-Pacific Strategy',
      primaryParentCompany: 'ANZ Banking Group',
      secondaryParentName: 'Michelle Young',
      secondaryParentRelation: 'Mother',
      secondaryParentPhone: '+91 98840 82220',
      secondaryParentEmail: 'michelle.young@woodsbagot.com',
      secondaryParentOccupation: 'Principal Landscape Architect',
      secondaryParentCompany: 'Woods Bagot Design Studio',
      emergencyContactName: 'Edward Young',
      emergencyContactRelation: 'Father',
      emergencyContactPhone: '+91 98840 71120',
      emergencyContactEmail: 'edward.young@anz.com',
      transportMode: 'School Bus #15 (Route 9 - Thiruvanmiyur)',
      busRoute: 'Route 9 - Thiruvanmiyur',
      busStop: 'Valmiki Nagar Beach Road',
      medicalNotes: 'No medical conditions · Editor of Student Literary Magazine',
      allergies: 'None',
      dietaryPreference: 'Vegetarian',
      attendance: 98,
      average: 95,
      gpa: '3.98 / 4.00',
      predictedScore: '43 / 45 (IBDP)',
      extendedEssayTopic: 'Strategic commitment and signaling games in bilateral tariff renegotiation equilibria',
      casHours: 160,
    },
    {
      name: 'Benjamin King',
      studentId: 'WB26021',
      admissionNumber: 'ADM-2024-1021',
      grade: 'Grade 12',
      homeroom: '12B',
      house: 'Hydra',
      homeroomTeacher: 'Mr. Pramod',
      homeroomTeacherEmail: 'mrpramod@westbridge.edu',
      homeroomTeacherPhone: '+91 98400 22005',
      counselor: 'Dr. Aisha Rahman',
      lockerNumber: 'L-226',
      dateOfBirth: '2008-08-20',
      gender: 'Male',
      bloodGroup: 'B-',
      nationality: 'British',
      studentEmail: 'benjamin.king@student.westbridge.edu',
      studentPhone: '+91 98401 55221',
      address: 'Bungalow 18, Coral Reef Enclave, 1st Avenue, Shastri Nagar, Adyar, Chennai - 600020',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600020',
      primaryParentName: 'Anthony King',
      primaryParentRelation: 'Father',
      primaryParentPhone: '+91 98840 71121',
      primaryParentEmail: 'anthony.king@bgs.ac.uk',
      primaryParentOccupation: 'Senior Geochemist',
      primaryParentCompany: 'British Geological Survey',
      secondaryParentName: 'Amanda King',
      secondaryParentRelation: 'Mother',
      secondaryParentPhone: '+91 98840 82221',
      secondaryParentEmail: 'amanda.king@barclays.com',
      secondaryParentOccupation: 'Managing Director - Capital Markets',
      secondaryParentCompany: 'Barclays Investment Bank',
      emergencyContactName: 'Anthony King',
      emergencyContactRelation: 'Father',
      emergencyContactPhone: '+91 98840 71121',
      emergencyContactEmail: 'anthony.king@bgs.ac.uk',
      transportMode: 'School Bus #12 (Route 4 - Adyar)',
      busRoute: 'Route 4 - Adyar',
      busStop: 'Shastri Nagar 1st Avenue',
      medicalNotes: 'No medical conditions · Cleared for athletics & rowing',
      allergies: 'None',
      dietaryPreference: 'Non-Vegetarian',
      attendance: 94,
      average: 89,
      gpa: '3.82 / 4.00',
      predictedScore: '39 / 45 (IBDP)',
      extendedEssayTopic: 'Enhanced atmospheric carbon dioxide sequestration via dunite and olivine powder dissolution in tropical soils',
      casHours: 120,
    },
    {
      name: 'Chloe Wright',
      studentId: 'WB26022',
      admissionNumber: 'ADM-2024-1022',
      grade: 'Grade 12',
      homeroom: '12B',
      house: 'Orion',
      homeroomTeacher: 'Dr. Rajesh Vasudevan',
      homeroomTeacherEmail: 'drrajeshvasudevan@westbridge.edu',
      homeroomTeacherPhone: '+91 98400 22006',
      counselor: 'Dr. Aisha Rahman',
      lockerNumber: 'L-227',
      dateOfBirth: '2008-01-29',
      gender: 'Female',
      bloodGroup: 'O+',
      nationality: 'American',
      studentEmail: 'chloe.wright@student.westbridge.edu',
      studentPhone: '+91 98401 55222',
      address: 'Apartment 1002, The Summit, 88 Cathedral Road, Gopalapuram, Chennai - 600086',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600086',
      primaryParentName: 'Jeffrey Wright',
      primaryParentRelation: 'Father',
      primaryParentPhone: '+91 98840 71122',
      primaryParentEmail: 'jeffrey.wright@afi.edu',
      primaryParentOccupation: 'Professor of Film Theory',
      primaryParentCompany: 'American Film Institute / Goethe-Institut',
      secondaryParentName: 'Dr. Elizabeth Wright',
      secondaryParentRelation: 'Mother',
      secondaryParentPhone: '+91 98840 82222',
      secondaryParentEmail: 'elizabeth.wright@fortis.com',
      secondaryParentOccupation: 'Head of Pediatric Orthopedics',
      secondaryParentCompany: 'Fortis Malar Hospital',
      emergencyContactName: 'Dr. Elizabeth Wright',
      emergencyContactRelation: 'Mother',
      emergencyContactPhone: '+91 98840 82222',
      emergencyContactEmail: 'elizabeth.wright@fortis.com',
      transportMode: 'Private Car / Parent Drop',
      busRoute: 'Self / Private Drop-off',
      busStop: 'Westbridge Main Entrance',
      medicalNotes: 'No medical conditions · Drama Club Lead Director',
      allergies: 'None',
      dietaryPreference: 'Vegetarian',
      attendance: 97,
      average: 94,
      gpa: '3.96 / 4.00',
      predictedScore: '42 / 45 (IBDP)',
      extendedEssayTopic: 'Temporal montage and existential dread in Alain Resnais and Chris Marker postwar French cinema',
      casHours: 150,
    },
    {
      name: 'Henry Scott',
      studentId: 'WB26023',
      admissionNumber: 'ADM-2024-1023',
      grade: 'Grade 12',
      homeroom: '12B',
      house: 'Aquila',
      homeroomTeacher: 'Dr. Rajesh Vasudevan',
      homeroomTeacherEmail: 'drrajeshvasudevan@westbridge.edu',
      homeroomTeacherPhone: '+91 98400 22006',
      counselor: 'Dr. Aisha Rahman',
      lockerNumber: 'L-228',
      dateOfBirth: '2008-06-07',
      gender: 'Male',
      bloodGroup: 'A+',
      nationality: 'Scottish',
      studentEmail: 'henry.scott@student.westbridge.edu',
      studentPhone: '+91 98401 55223',
      address: 'Villa 9, Tamarind Grove, Turnbulls Road, Nandanam, Chennai - 600035',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600035',
      primaryParentName: 'Donald Scott',
      primaryParentRelation: 'Father',
      primaryParentPhone: '+91 98840 71123',
      primaryParentEmail: 'donald.scott@bailliegifford.com',
      primaryParentOccupation: 'Chief Investment Officer - Asia',
      primaryParentCompany: 'Baillie Gifford Asset Management',
      secondaryParentName: 'Margaret Scott',
      secondaryParentRelation: 'Mother',
      secondaryParentPhone: '+91 98840 82223',
      secondaryParentEmail: 'margaret.scott@linklaters.com',
      secondaryParentOccupation: 'Senior Corporate Counsel',
      secondaryParentCompany: 'Linklaters Law Firm',
      emergencyContactName: 'Donald Scott',
      emergencyContactRelation: 'Father',
      emergencyContactPhone: '+91 98840 71123',
      emergencyContactEmail: 'donald.scott@bailliegifford.com',
      transportMode: 'School Bus #08 (Route 7 - Nandanam)',
      busRoute: 'Route 7 - Nandanam',
      busStop: 'Turnbulls Road Junction',
      medicalNotes: 'No medical conditions · Math Olympiad Team Lead',
      allergies: 'None',
      dietaryPreference: 'Non-Vegetarian',
      attendance: 98,
      average: 96,
      gpa: '4.00 / 4.00',
      predictedScore: '44 / 45 (IBDP)',
      extendedEssayTopic: 'Stochastic volatility modeling: Empirical validation of the Heston framework using intraday equity index options',
      casHours: 135,
    },
    {
      name: 'Grace Green',
      studentId: 'WB26024',
      admissionNumber: 'ADM-2024-1024',
      grade: 'Grade 12',
      homeroom: '12B',
      house: 'Centaurus',
      homeroomTeacher: 'Dr. Rajesh Vasudevan',
      homeroomTeacherEmail: 'drrajeshvasudevan@westbridge.edu',
      homeroomTeacherPhone: '+91 98400 22006',
      counselor: 'Dr. Aisha Rahman',
      lockerNumber: 'L-229',
      dateOfBirth: '2008-11-16',
      gender: 'Female',
      bloodGroup: 'AB-',
      nationality: 'Irish',
      studentEmail: 'grace.green@student.westbridge.edu',
      studentPhone: '+91 98401 55224',
      address: 'Flat 301, Casa Grande Royale, 1st Cross Street, Gandhi Nagar, Adyar, Chennai - 600020',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600020',
      primaryParentName: 'Patrick Green',
      primaryParentRelation: 'Father',
      primaryParentPhone: '+91 98840 71124',
      primaryParentEmail: 'patrick.green@crh.com',
      primaryParentOccupation: 'Director of Environmental Sustainability',
      primaryParentCompany: 'CRH Sustainable Materials',
      secondaryParentName: 'Hannah Green',
      secondaryParentRelation: 'Mother',
      secondaryParentPhone: '+91 98840 82224',
      secondaryParentEmail: 'hannah.green@tcd.ie',
      secondaryParentOccupation: 'Lecturer in Plant Ecology',
      secondaryParentCompany: 'Trinity College Dublin / University of Madras',
      emergencyContactName: 'Patrick Green',
      emergencyContactRelation: 'Father',
      emergencyContactPhone: '+91 98840 71124',
      emergencyContactEmail: 'patrick.green@crh.com',
      transportMode: 'Bicycle / Green Commute',
      busRoute: 'Self / Bicycle Route',
      busStop: 'Westbridge Bike Station',
      medicalNotes: 'No medical conditions · Eco-Club President',
      allergies: 'None',
      dietaryPreference: 'Vegetarian',
      attendance: 96,
      average: 93,
      gpa: '3.94 / 4.00',
      predictedScore: '42 / 45 (IBDP)',
      extendedEssayTopic: 'Extracellular electron transfer kinetics of Shewanella oneidensis in dual-chamber microbial fuel cell bioreactors',
      casHours: 175,
    },
    {
      name: 'Daniel Adams',
      studentId: 'WB26025',
      admissionNumber: 'ADM-2024-1025',
      grade: 'Grade 12',
      homeroom: '12B',
      house: 'Phoenix',
      homeroomTeacher: 'Ms. Brindha',
      homeroomTeacherEmail: 'msbrindha@westbridge.edu',
      homeroomTeacherPhone: '+91 98400 22007',
      counselor: 'Dr. Aisha Rahman',
      lockerNumber: 'L-230',
      dateOfBirth: '2008-04-28',
      gender: 'Male',
      bloodGroup: 'O+',
      nationality: 'American',
      studentEmail: 'daniel.adams@student.westbridge.edu',
      studentPhone: '+91 98401 55225',
      address: 'House 24, Blue Lagoon Enclave, ECR, Injambakkam, Chennai, Tamil Nadu - 600115',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600115',
      primaryParentName: 'Gregory Adams',
      primaryParentRelation: 'Father',
      primaryParentPhone: '+91 98840 71125',
      primaryParentEmail: 'gregory.adams@nasa.gov',
      primaryParentOccupation: 'Senior Research Astrophysicist',
      primaryParentCompany: 'NASA Goddard / ISRO Liaison',
      secondaryParentName: 'Diana Adams',
      secondaryParentRelation: 'Mother',
      secondaryParentPhone: '+91 98840 82225',
      secondaryParentEmail: 'diana.adams@apple.com',
      secondaryParentOccupation: 'Senior Director of Data Engineering',
      secondaryParentCompany: 'Apple Inc.',
      emergencyContactName: 'Diana Adams',
      emergencyContactRelation: 'Mother',
      emergencyContactPhone: '+91 98840 82225',
      emergencyContactEmail: 'diana.adams@apple.com',
      transportMode: 'School Bus #22 (Route 11 - ECR Injambakkam)',
      busRoute: 'Route 11 - ECR Injambakkam',
      busStop: 'Injambakkam Prarthana Drive-in Stop',
      medicalNotes: 'No medical conditions · Astronomy Society President',
      allergies: 'None',
      dietaryPreference: 'Non-Vegetarian',
      attendance: 95,
      average: 91,
      gpa: '3.90 / 4.00',
      predictedScore: '41 / 45 (IBDP)',
      extendedEssayTopic: 'Magnetohydrodynamic simulations of relativistic plasma jets and accretion disk turbulence in active galactic nuclei',
      casHours: 140,
    },
    {
      name: 'Lily Baker',
      studentId: 'WB26026',
      admissionNumber: 'ADM-2024-1026',
      grade: 'Grade 12',
      homeroom: '12B',
      house: 'Pegasus',
      homeroomTeacher: 'Ms. Brindha',
      homeroomTeacherEmail: 'msbrindha@westbridge.edu',
      homeroomTeacherPhone: '+91 98400 22007',
      counselor: 'Dr. Aisha Rahman',
      lockerNumber: 'L-231',
      dateOfBirth: '2008-09-21',
      gender: 'Female',
      bloodGroup: 'A-',
      nationality: 'Australian',
      studentEmail: 'lily.baker@student.westbridge.edu',
      studentPhone: '+91 98401 55226',
      address: 'Apartment 15A, The Marina Crest, Kothari Road, Nungambakkam, Chennai - 600034',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600034',
      primaryParentName: 'Dennis Baker',
      primaryParentRelation: 'Father',
      primaryParentPhone: '+91 98840 71126',
      primaryParentEmail: 'dennis.baker@atlassian.com',
      primaryParentOccupation: 'VP of Platform Infrastructure',
      primaryParentCompany: 'Atlassian Global',
      secondaryParentName: 'Dr. Christine Baker',
      secondaryParentRelation: 'Mother',
      secondaryParentPhone: '+91 98840 82226',
      secondaryParentEmail: 'christine.baker@unimelb.edu.au',
      secondaryParentOccupation: 'Associate Professor of Developmental Psychology',
      secondaryParentCompany: 'University of Melbourne',
      emergencyContactName: 'Dennis Baker',
      emergencyContactRelation: 'Father',
      emergencyContactPhone: '+91 98840 71126',
      emergencyContactEmail: 'dennis.baker@atlassian.com',
      transportMode: 'School Bus #19 (Route 3 - Nungambakkam)',
      busRoute: 'Route 3 - Nungambakkam',
      busStop: 'Kothari Road Corner',
      medicalNotes: 'No medical conditions · Model UN Secretary General',
      allergies: 'None',
      dietaryPreference: 'Vegetarian',
      attendance: 98,
      average: 95,
      gpa: '3.98 / 4.00',
      predictedScore: '43 / 45 (IBDP)',
      extendedEssayTopic: 'Algorithmic reinforcement of confirmation bias in personalized recommendation feeds: A behavioral experiment',
      casHours: 165,
    },
    {
      name: 'Samuel Nelson',
      studentId: 'WB26027',
      admissionNumber: 'ADM-2024-1027',
      grade: 'Grade 12',
      homeroom: '12B',
      house: 'Hydra',
      homeroomTeacher: 'Ms. Brindha',
      homeroomTeacherEmail: 'msbrindha@westbridge.edu',
      homeroomTeacherPhone: '+91 98400 22007',
      counselor: 'Dr. Aisha Rahman',
      lockerNumber: 'L-232',
      dateOfBirth: '2008-02-14',
      gender: 'Male',
      bloodGroup: 'B+',
      nationality: 'American',
      studentEmail: 'samuel.nelson@student.westbridge.edu',
      studentPhone: '+91 98401 55227',
      address: 'House 7B, Seaward Enclave, 2nd Seaward Road, Valmiki Nagar, Thiruvanmiyur, Chennai - 600041',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600041',
      primaryParentName: 'Dr. Raymond Nelson',
      primaryParentRelation: 'Father',
      primaryParentPhone: '+91 98840 71127',
      primaryParentEmail: 'raymond.nelson@3m.com',
      primaryParentOccupation: 'Chief Materials Scientist',
      primaryParentCompany: '3M Research & Development',
      secondaryParentName: 'Dr. Evelyn Nelson',
      secondaryParentRelation: 'Mother',
      secondaryParentPhone: '+91 98840 82227',
      secondaryParentEmail: 'evelyn.nelson@apollochildrens.com',
      secondaryParentOccupation: 'Head of Pediatric Intensive Care',
      secondaryParentCompany: 'Apollo Children’s Hospital',
      emergencyContactName: 'Dr. Raymond Nelson',
      emergencyContactRelation: 'Father',
      emergencyContactPhone: '+91 98840 71127',
      emergencyContactEmail: 'raymond.nelson@3m.com',
      transportMode: 'School Bus #15 (Route 9 - Thiruvanmiyur)',
      busRoute: 'Route 9 - Thiruvanmiyur',
      busStop: 'Seaward Road Entrance',
      medicalNotes: 'No medical conditions · Cleared for competitive basketball',
      allergies: 'None',
      dietaryPreference: 'Non-Vegetarian',
      attendance: 96,
      average: 92,
      gpa: '3.92 / 4.00',
      predictedScore: '41 / 45 (IBDP)',
      extendedEssayTopic: 'Chemical vapor deposition growth parameters for defect-free graphene electrodes in high-energy supercapacitors',
      casHours: 130,
    },
    {
      name: 'Zoe Carter',
      studentId: 'WB26028',
      admissionNumber: 'ADM-2024-1028',
      grade: 'Grade 12',
      homeroom: '12B',
      house: 'Orion',
      homeroomTeacher: 'Ms. Brindha',
      homeroomTeacherEmail: 'msbrindha@westbridge.edu',
      homeroomTeacherPhone: '+91 98400 22007',
      counselor: 'Dr. Aisha Rahman',
      lockerNumber: 'L-233',
      dateOfBirth: '2008-08-09',
      gender: 'Female',
      bloodGroup: 'O-',
      nationality: 'Canadian',
      studentEmail: 'zoe.carter@student.westbridge.edu',
      studentPhone: '+91 98401 55228',
      address: 'Villa 11, Green Meadows, 4th Main Road, Gandhi Nagar, Adyar, Chennai - 600020',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600020',
      primaryParentName: 'Bradley Carter',
      primaryParentRelation: 'Father',
      primaryParentPhone: '+91 98840 71128',
      primaryParentEmail: 'bradley.carter@who.int',
      primaryParentOccupation: 'Country Director for Health Systems',
      primaryParentCompany: 'World Health Organization (WHO)',
      secondaryParentName: 'Teresa Carter',
      secondaryParentRelation: 'Mother',
      secondaryParentPhone: '+91 98840 82228',
      secondaryParentEmail: 'teresa.carter@worldbank.org',
      secondaryParentOccupation: 'Lead Development Economist',
      secondaryParentCompany: 'The World Bank Group',
      emergencyContactName: 'Bradley Carter',
      emergencyContactRelation: 'Father',
      emergencyContactPhone: '+91 98840 71128',
      emergencyContactEmail: 'bradley.carter@who.int',
      transportMode: 'School Bus #12 (Route 4 - Adyar)',
      busRoute: 'Route 4 - Adyar',
      busStop: 'Gandhi Nagar 4th Main Road',
      medicalNotes: 'No medical conditions · Student Council Vice President',
      allergies: 'None',
      dietaryPreference: 'Vegetarian',
      attendance: 99,
      average: 97,
      gpa: '4.00 / 4.00',
      predictedScore: '44 / 45 (IBDP)',
      extendedEssayTopic: 'Empirical assessment of conditional cash transfers on maternal healthcare utilization in rural Tamil Nadu',
      casHours: 190,
    },
    {
      name: 'Jacob Mitchell',
      studentId: 'WB26029',
      admissionNumber: 'ADM-2024-1029',
      grade: 'Grade 12',
      homeroom: '12B',
      house: 'Aquila',
      homeroomTeacher: 'Ms. Brindha',
      homeroomTeacherEmail: 'msbrindha@westbridge.edu',
      homeroomTeacherPhone: '+91 98400 22007',
      counselor: 'Dr. Aisha Rahman',
      lockerNumber: 'L-234',
      dateOfBirth: '2008-03-24',
      gender: 'Male',
      bloodGroup: 'AB+',
      nationality: 'American',
      studentEmail: 'jacob.mitchell@student.westbridge.edu',
      studentPhone: '+91 98401 55229',
      address: 'Apartment 801, Ceebros Heritage, 12 Santhome High Road, Mylapore, Chennai - 600004',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600004',
      primaryParentName: 'Scott Mitchell',
      primaryParentRelation: 'Father',
      primaryParentPhone: '+91 98840 71129',
      primaryParentEmail: 'scott.mitchell@boeing.com',
      primaryParentOccupation: 'VP of Flight Systems & Avionics',
      primaryParentCompany: 'Boeing Defense & Space',
      secondaryParentName: 'Andrea Mitchell',
      secondaryParentRelation: 'Mother',
      secondaryParentPhone: '+91 98840 82229',
      secondaryParentEmail: 'andrea.mitchell@goldmansachs.com',
      secondaryParentOccupation: 'Managing Director - Financial Operations',
      secondaryParentCompany: 'Goldman Sachs',
      emergencyContactName: 'Scott Mitchell',
      emergencyContactRelation: 'Father',
      emergencyContactPhone: '+91 98840 71129',
      emergencyContactEmail: 'scott.mitchell@boeing.com',
      transportMode: 'School Bus #12 (Route 4 - Mylapore)',
      busRoute: 'Route 4 - Mylapore',
      busStop: 'Santhome High Road Stop',
      medicalNotes: 'No medical conditions · Varsity Athletics Captain',
      allergies: 'None',
      dietaryPreference: 'Non-Vegetarian',
      attendance: 94,
      average: 90,
      gpa: '3.88 / 4.00',
      predictedScore: '40 / 45 (IBDP)',
      extendedEssayTopic: 'Spectral element methods for direct numerical simulation of turbulent boundary layer separation on supercritical airfoils',
      casHours: 125,
    },
    {
      name: 'Nora Roberts',
      studentId: 'WB26030',
      admissionNumber: 'ADM-2024-1030',
      grade: 'Grade 12',
      homeroom: '12B',
      house: 'Centaurus',
      homeroomTeacher: 'Ms. Brindha',
      homeroomTeacherEmail: 'msbrindha@westbridge.edu',
      homeroomTeacherPhone: '+91 98400 22007',
      counselor: 'Dr. Aisha Rahman',
      lockerNumber: 'L-235',
      dateOfBirth: '2008-10-31',
      gender: 'Female',
      bloodGroup: 'A+',
      nationality: 'British',
      studentEmail: 'nora.roberts@student.westbridge.edu',
      studentPhone: '+91 98401 55230',
      address: 'Villa 15, Palm Springs Enclave, Boat Club Road, RA Puram, Chennai, Tamil Nadu - 600028',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600028',
      primaryParentName: 'Douglas Roberts',
      primaryParentRelation: 'Father',
      primaryParentPhone: '+91 98840 71130',
      primaryParentEmail: 'douglas.roberts@syngenta.com',
      primaryParentOccupation: 'Chief Agricultural Geneticist',
      primaryParentCompany: 'Syngenta Global Seeds',
      secondaryParentName: 'Dr. Kelly Roberts',
      secondaryParentRelation: 'Mother',
      secondaryParentPhone: '+91 98840 82230',
      secondaryParentEmail: 'kelly.roberts@cam.ac.uk',
      secondaryParentOccupation: 'Consultant Clinical Geneticist',
      secondaryParentCompany: 'University of Cambridge / Apollo Health',
      emergencyContactName: 'Dr. Kelly Roberts',
      emergencyContactRelation: 'Mother',
      emergencyContactPhone: '+91 98840 82230',
      emergencyContactEmail: 'kelly.roberts@cam.ac.uk',
      transportMode: 'Private Car / Parent Drop',
      busRoute: 'Self / Private Drop-off',
      busStop: 'Westbridge North Gate',
      medicalNotes: 'No medical conditions · Head of School Science Fair Committee',
      allergies: 'None',
      dietaryPreference: 'Vegetarian',
      attendance: 98,
      average: 96,
      gpa: '4.00 / 4.00',
      predictedScore: '44 / 45 (IBDP)',
      extendedEssayTopic: 'Engineered nitrogen fixation in Rhizobium leguminosarum strains using CRISPR-dCas9 metabolic activation',
      casHours: 175,
    },
  ];

  studentProfiles.forEach((profile, i) => {
    add('student', profile.name, {
      ...profile,
      class: classes[i % 6],
      status: 'Active',
      updatedAt: '2026-09-18T07:30:00Z',
    });
  });

  // Academic Classes
  classes.forEach((name, i) =>
    add('class', name, {
      teacher: [
        'Ms. Shalaba',
        'Dr. Mallu',
        'Mr. Rishikesh',
        'Mr. Pramod',
        'Dr. Rajesh Vasudevan & Ms. Sangeetha',
        'Ms. Brindha',
      ][i],
      room: ['Lab 101', 'Lab 103', 'Lab 102', 'Room 204', 'Room 108', 'Room 210'][i],
      time: ['08:30', '09:30', '10:45', '11:45', '13:30', '14:30'][i],
      department: [
        'Science',
        'Science',
        'Humanities & Tech',
        'Mathematics',
        'Languages & Literature',
        'Languages',
      ][i],
    }),
  );

  // Assignments
  const assignmentsList = [
    'Forces and motion investigation',
    'Acid–base titration report',
    'Cell structure worksheet',
    'Differentiation practice',
    'Literary analysis essay',
    'Market structures case study',
    'Waves lab reflection',
    'Reaction kinetics investigation',
    'Genetics problem set',
    'Integration exploration',
    'Individual oral preparation',
    'Inflation research brief',
    'Electric circuits analysis',
    'Organic chemistry revision',
    'Ecology field study',
  ];

  assignmentsList.forEach((name, i) =>
    add('assignment', name, {
      class: classes[i % 6],
      dueAt: `2026-09-${String(8 + i).padStart(2, '0')}T16:00`,
      maximumMarks: i % 3 === 0 ? 30 : 20,
      status: 'Published',
      instructions:
        'Complete the task using the methods discussed in class. Show your reasoning, cite any sources, and submit your written response before the deadline.',
      type: 'text',
    }),
  );

  // Student Submissions for Assignments
  for (let s = 0; s < 30; s++) {
    const studentId = `student-${s + 1}`;
    const studentName = students[s];
    const assignmentIdx = s % assignmentsList.length;
    add('submission', `${assignmentsList[assignmentIdx]} - ${studentName}`, {
      studentId,
      studentName,
      assignmentId: `assignment-${assignmentIdx + 1}`,
      assignmentName: assignmentsList[assignmentIdx],
      class: classes[s % 6],
      score: 18 + (s % 3),
      maximumMarks: 20,
      grade: s % 5 === 0 ? '7 (High 7)' : '6 (Solid 6)',
      status: 'Graded',
      feedback: 'Excellent rigor, thorough citations and well-structured analytical conclusions.',
      submittedAt: '2026-09-08T14:20:00Z',
    });
  }

  // Student Attendance Records for Today and Past Days
  const dates = ['2026-09-18', '2026-09-17', '2026-09-16', '2026-09-15'];
  dates.forEach((date) => {
    for (let s = 0; s < 30; s++) {
      const studentId = `student-${s + 1}`;
      const studentName = students[s];
      add('attendance', `Attendance - ${studentName} (${date})`, {
        studentId,
        studentName,
        date,
        period: 'Daily Homeroom',
        status: (s + date.length) % 17 === 0 ? 'Late' : 'Present',
        notes: (s + date.length) % 17 === 0 ? 'Traffic delay on ECR route' : 'On time',
        recordedBy: studentProfiles[s].homeroomTeacher,
      });
    }
  });

  // Student Behaviour & Commendation Records
  for (let i = 0; i < 30; i++) {
    const studentId = `student-${i + 1}`;
    const studentName = students[i];
    const isCommendation = i % 2 === 0;

    add('record', isCommendation ? 'Academic Excellence & Leadership' : 'Punctuality & Lab Safety Commendation', {
      studentId,
      studentName,
      category: isCommendation ? 'Positive behaviour' : 'Lab Safety Commendation',
      description: isCommendation
        ? 'Demonstrated outstanding leadership and rigorous collaborative inquiry during the group research phase.'
        : 'Exemplary adherence to laboratory safety protocols and precise equipment handling.',
      severity: 'Low',
      actionTaken: 'Formal commendation entered in SchoolOS master profile and shared with parents.',
      studentVisible: true,
      internalNotes: 'Consistent high performer and positive contributor to class culture.',
      occurredAt: `2026-09-${String(10 + (i % 8)).padStart(2, '0')}`,
      status: 'Closed',
      reportedBy: studentProfiles[i].homeroomTeacher,
    });
  }

  // System Notifications
  for (let i = 0; i < 10; i++)
    add(
      'notification',
      [
        'Welcome to the new academic year 2026-27',
        'Lab inventory and safety manifests updated',
        'Library reading lists & digital journals available',
        'Term 1 IB DP internal assessment deadlines published',
        'Term 1 Master Timetable and room allocations live',
      ][i % 5],
      {
        description:
          'Open the linked SchoolOS workspace module to review the latest verified details.',
        target: ['Home', 'Labs', 'Library', 'Academics', 'Calendar'][i % 5],
        read: false,
        date: '2026-09-18',
      },
    );

  // Lab Requests for Students
  for (let i = 0; i < 30; i++) {
    const studentId = `student-${i + 1}`;
    const studentName = students[i];
    const inventoryItem = out.filter((x) => x.kind === 'inventory')[i % 20];
    add('request', `${inventoryItem.name} - ${studentName}`, {
      itemId: inventoryItem.id,
      itemName: inventoryItem.name,
      type: 'lab',
      quantity: (i % 2) + 1,
      purpose: 'IB DP Experimental Internal Assessment Practical',
      class: classes[i % 6],
      teacher: studentProfiles[i].homeroomTeacher,
      desiredDate: '2026-09-22',
      status: i % 3 === 0 ? 'Approved' : 'Completed',
      studentId,
      studentName,
    });
  }

  // Library Loans for Students
  for (let i = 0; i < 30; i++) {
    const studentId = `student-${i + 1}`;
    const studentName = students[i];
    const title = titles[(i + 3) % titles.length];
    add('loan', `${title[0]} - ${studentName}`, {
      bookId: `book-${((i + 3) % titles.length) + 1}`,
      bookTitle: title[0],
      author: title[1],
      studentId,
      studentName,
      borrowedAt: '2026-09-05',
      dueAt: '2026-09-25',
      status: 'Borrowed',
    });
  }

  // Staff Profiles
  [
    'Dr. Sarah Mitchell',
    'David Park',
    'Dr. Maya Rao',
    'James Wilson',
    'Emily Thompson',
    'Michael Brooks',
    'Olivia Reed',
    'Daniel Moore',
    'Priya Nair',
    'Thomas Evans',
    'Ravi Kumar',
    'Helen Shaw',
    'Amir Khan',
    'Alex Carter',
    'Sam Rivera',
  ].forEach((name, i) =>
    add('staff', name, {
      role:
        i < 8
          ? 'Teacher'
          : i < 11
            ? 'Lab Assistant'
            : i < 13
              ? 'Librarian'
              : 'Admin',
      email: `${name.toLowerCase().replace(/[^a-z]/g, '')}@westbridge.edu`,
      phone: `+91 98400 ${String(30000 + i * 222).slice(0, 5)}`,
      department: i < 8 ? 'Academics' : i < 11 ? 'Science Laboratories' : i < 13 ? 'Library Services' : 'Operations & Leadership',
      status: 'Active',
    }),
  );
  return out;
}
