-- SchoolOS Supabase foundation. Apply with `supabase db push` from a secured
-- server/developer environment; no application credential is stored here.
create extension if not exists pgcrypto;

create type public.school_role as enum ('student','teacher','lab_assistant','librarian','transport_staff','staff','admin','head_of_school');
create type public.damage_status as enum ('Reported','UnderReview','ActionRequired','Resolved','Closed');

create table public.organizations (id uuid primary key default gen_random_uuid(), external_id text unique, name text not null, school_year text, owner_id uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, organization_id uuid not null references public.organizations(id) on delete cascade, display_name text not null, email text not null, avatar_url text, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id,email));
create table public.roles (id uuid primary key default gen_random_uuid(), code public.school_role not null unique, label text not null);
create table public.user_roles (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, role_id uuid not null references public.roles(id), created_at timestamptz not null default now(), unique(organization_id,user_id,role_id));
create table public.role_permissions (role_id uuid not null references public.roles(id) on delete cascade, permission text not null, primary key(role_id,permission));
create table public.departments (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, external_id text not null, name text not null, created_at timestamptz not null default now(), unique(organization_id,external_id));
create table public.students (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, profile_id uuid unique references public.profiles(id) on delete set null, external_id text not null, grade text, house text, created_at timestamptz not null default now(), unique(organization_id,external_id));
create table public.teachers (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, profile_id uuid unique references public.profiles(id) on delete set null, external_id text not null, department_id uuid references public.departments(id) on delete set null, created_at timestamptz not null default now(), unique(organization_id,external_id));
create table public.staff (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, profile_id uuid unique references public.profiles(id) on delete set null, external_id text not null, department_id uuid references public.departments(id) on delete set null, created_at timestamptz not null default now(), unique(organization_id,external_id));
create table public.classes (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, external_id text not null, department_id uuid references public.departments(id) on delete set null, title text not null, grade text, subject text, homeroom_teacher_id uuid references public.teachers(id) on delete set null, created_at timestamptz not null default now(), unique(organization_id,external_id));
create table public.class_memberships (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, class_id uuid not null references public.classes(id) on delete cascade, student_id uuid references public.students(id) on delete cascade, teacher_id uuid references public.teachers(id) on delete cascade, membership_role text not null check(membership_role in ('student','subject_teacher','class_teacher','assistant')), created_at timestamptz not null default now(), check((student_id is not null)::int + (teacher_id is not null)::int = 1));

-- Universal, queryable tracking store used by repositories. The domain tables
-- below retain normalized workflow data; tags never replace their foreign keys.
create table public.tracked_records (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, entity_type text not null, record_type text not null, source_module text not null, status text, student_id uuid references public.students(id) on delete set null, teacher_id uuid references public.teachers(id) on delete set null, class_id uuid references public.classes(id) on delete set null, asset_id uuid, tags text[] not null default '{}', labels text[] not null default '{}', metadata jsonb not null default '{}', related_entity_refs jsonb not null default '[]', visibility jsonb not null default '{"adminVisible":true}', body jsonb not null default '{}', created_by uuid references public.profiles(id) on delete set null, updated_by uuid references public.profiles(id) on delete set null, audit_id uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index tracked_records_org_lookup on public.tracked_records(organization_id,source_module,record_type,status,created_at desc);
create index tracked_records_tags on public.tracked_records using gin(tags);
create index tracked_records_search on public.tracked_records using gin((body || metadata));

create table public.attendance_records (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, class_id uuid not null references public.classes(id) on delete cascade, date date not null, status text not null, marked_by uuid references public.profiles(id) on delete set null, note text, tracked_record_id uuid references public.tracked_records(id) on delete set null, unique(organization_id,student_id,class_id,date));
create table public.teacher_class_logs (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, class_id uuid not null references public.classes(id) on delete cascade, teacher_id uuid references public.teachers(id) on delete set null, title text not null, lesson_date date not null, content jsonb not null default '{}', tracked_record_id uuid references public.tracked_records(id) on delete set null, created_at timestamptz not null default now());
create table public.student_records (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, class_id uuid references public.classes(id) on delete set null, record_type text not null, title text not null, description text, action_taken text, student_visible boolean not null default false, parent_visible boolean not null default false, restricted boolean not null default false, private_notes text, reported_by uuid references public.profiles(id) on delete set null, tracked_record_id uuid references public.tracked_records(id) on delete set null, created_at timestamptz not null default now());
create table public.damage_records (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, student_id uuid references public.students(id) on delete set null, staff_id uuid references public.staff(id) on delete set null, class_id uuid references public.classes(id) on delete set null, module text not null, asset_type text not null, asset_id uuid, asset_name text not null, quantity numeric, condition_before text, condition_after text, damage_type text not null, severity text not null, description text not null, date_time timestamptz not null, location text, reported_by uuid references public.profiles(id) on delete set null, assigned_to uuid references public.profiles(id) on delete set null, status public.damage_status not null default 'Reported', student_visible boolean not null default false, action_taken text, cost_estimate numeric, resolution text, tracked_record_id uuid references public.tracked_records(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create table public.assignments (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, class_id uuid not null references public.classes(id) on delete cascade, teacher_id uuid references public.teachers(id) on delete set null, title text not null, description text, due_at timestamptz, status text not null default 'Draft', tracked_record_id uuid references public.tracked_records(id) on delete set null, created_at timestamptz not null default now());
create table public.submissions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, assignment_id uuid not null references public.assignments(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, response text, attachments jsonb not null default '[]', status text not null default 'Draft', submitted_at timestamptz, tracked_record_id uuid references public.tracked_records(id) on delete set null, unique(assignment_id,student_id));
create table public.grades (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, submission_id uuid references public.submissions(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, class_id uuid references public.classes(id) on delete set null, score numeric, maximum_score numeric, feedback text, published boolean not null default false, graded_by uuid references public.profiles(id) on delete set null, tracked_record_id uuid references public.tracked_records(id) on delete set null, created_at timestamptz not null default now());
create table public.resources (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, class_id uuid references public.classes(id) on delete cascade, title text not null, storage_path text, visibility text not null default 'class', created_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now());

create table public.lab_items (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, external_id text not null, lab text not null, category text not null, name text not null, quantity numeric not null default 0, unit text not null, location text, condition text, availability text, unit_cost numeric, created_at timestamptz not null default now(), unique(organization_id,external_id));
create table public.lab_requests (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, item_id uuid references public.lab_items(id) on delete set null, requester_id uuid references public.profiles(id) on delete set null, student_id uuid references public.students(id) on delete set null, teacher_id uuid references public.teachers(id) on delete set null, class_id uuid references public.classes(id) on delete set null, quantity numeric not null, purpose text, request_date date not null default current_date, status text not null default 'Pending', decision_by uuid references public.profiles(id) on delete set null, decision_at timestamptz, tracked_record_id uuid references public.tracked_records(id) on delete set null);
create table public.lab_usage (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, item_id uuid not null references public.lab_items(id) on delete restrict, quantity numeric not null, student_id uuid references public.students(id) on delete set null, teacher_id uuid references public.teachers(id) on delete set null, class_id uuid references public.classes(id) on delete set null, experiment text, used_at timestamptz not null default now(), issued_by uuid references public.profiles(id) on delete set null, returned_quantity numeric, consumed_quantity numeric, condition_after text, tracked_record_id uuid references public.tracked_records(id) on delete set null);
create table public.lab_transactions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, item_id uuid not null references public.lab_items(id) on delete restrict, transaction_type text not null, quantity numeric not null, before_quantity numeric, after_quantity numeric, actor_id uuid references public.profiles(id) on delete set null, related_usage_id uuid references public.lab_usage(id) on delete set null, created_at timestamptz not null default now(), tracked_record_id uuid references public.tracked_records(id) on delete set null);
create table public.lab_orders (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, supplier text, status text not null default 'Draft', priority text, requested_by uuid references public.profiles(id) on delete set null, requested_at timestamptz not null default now(), estimated_cost numeric, notes text, approval_history jsonb not null default '[]', tracked_record_id uuid references public.tracked_records(id) on delete set null);
create table public.lab_order_items (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.lab_orders(id) on delete cascade, item_id uuid references public.lab_items(id) on delete set null, item_name text not null, category text, quantity numeric not null, unit text, estimated_cost numeric, received_quantity numeric not null default 0);

create table public.library_books (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, external_id text not null, isbn text, title text not null, author text not null, category text, cover_path text, created_at timestamptz not null default now(), unique(organization_id,external_id));
create table public.book_copies (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, book_id uuid not null references public.library_books(id) on delete cascade, barcode text not null, location text, condition text, availability text not null default 'Available', unique(organization_id,barcode));
create table public.borrow_transactions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, copy_id uuid not null references public.book_copies(id) on delete restrict, student_id uuid references public.students(id) on delete set null, teacher_id uuid references public.teachers(id) on delete set null, issued_by uuid references public.profiles(id) on delete set null, issued_at timestamptz not null default now(), due_at timestamptz, returned_at timestamptz, status text not null default 'Borrowed', condition_out text, condition_in text, tracked_record_id uuid references public.tracked_records(id) on delete set null);
create table public.book_requests (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, requester_id uuid references public.profiles(id) on delete set null, title text not null, author text, reason text, status text not null default 'Pending', created_at timestamptz not null default now(), tracked_record_id uuid references public.tracked_records(id) on delete set null);

create table public.calendar_events (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, class_id uuid references public.classes(id) on delete set null, title text not null, starts_at timestamptz not null, ends_at timestamptz, audience text not null default 'school', details jsonb not null default '{}');
create table public.timetables (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, class_id uuid references public.classes(id) on delete cascade, teacher_id uuid references public.teachers(id) on delete set null, day_of_week integer not null check(day_of_week between 0 and 6), starts_at time not null, ends_at time not null, room text, period text);
create table public.exams (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, class_id uuid references public.classes(id) on delete cascade, title text not null, starts_at timestamptz not null, ends_at timestamptz, results_published boolean not null default false, details jsonb not null default '{}');
create table public.cas_experiences (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, title text not null, strand text not null, status text not null default 'Draft', evidence jsonb not null default '[]', tracked_record_id uuid references public.tracked_records(id) on delete set null);
create table public.projects (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, title text not null, supervisor_id uuid references public.teachers(id) on delete set null, status text not null default 'Active', details jsonb not null default '{}');
create table public.project_members (project_id uuid not null references public.projects(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, primary key(project_id,student_id));
create table public.project_milestones (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, project_id uuid not null references public.projects(id) on delete cascade, title text not null, due_at timestamptz, status text not null default 'Open');
create table public.transport_notices (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, notice_date date not null, route text, bus text, change_type text not null, reason text, pickup text, dropoff text, notes text, status text not null default 'Submitted', submitted_by uuid references public.profiles(id) on delete set null, submitted_at timestamptz not null default now(), operational_note text, student_visible boolean not null default true, tracked_record_id uuid references public.tracked_records(id) on delete set null, unique(organization_id,student_id,notice_date,change_type));
create table public.buses (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, bus_code text not null, route text, driver text, assistant text, capacity integer, status text not null default 'Active', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id,bus_code));
create table public.bus_arrival_records (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, bus_id uuid not null references public.buses(id) on delete cascade, arrival_date date not null, scheduled_arrival_time time, actual_arrival_time time, arrival_status text not null, late_minutes integer, late_reason text, notes text, recorded_by uuid references public.profiles(id) on delete set null, tracked_record_id uuid references public.tracked_records(id) on delete set null, created_at timestamptz not null default now(), unique(organization_id,bus_id,arrival_date));
create table public.bus_departure_records (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, bus_id uuid not null references public.buses(id) on delete cascade, departure_date date not null, scheduled_departure_time time, actual_departure_time time, departure_status text not null, delay_minutes integer, delay_reason text, notes text, recorded_by uuid references public.profiles(id) on delete set null, tracked_record_id uuid references public.tracked_records(id) on delete set null, created_at timestamptz not null default now(), unique(organization_id,bus_id,departure_date));
create table public.transport_activity (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, activity_type text not null, bus_id uuid references public.buses(id) on delete set null, notice_id uuid references public.transport_notices(id) on delete set null, actor_id uuid references public.profiles(id) on delete set null, details jsonb not null default '{}', tracked_record_id uuid references public.tracked_records(id) on delete set null, created_at timestamptz not null default now());
create table public.maintenance_reports (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, reporter_id uuid references public.profiles(id) on delete set null, location text not null, title text not null, description text, status text not null default 'Reported', image_paths jsonb not null default '[]', tracked_record_id uuid references public.tracked_records(id) on delete set null, created_at timestamptz not null default now());
create table public.inquiries (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, created_by uuid references public.profiles(id) on delete set null, assigned_to uuid references public.profiles(id) on delete set null, subject text not null, status text not null default 'Open', restricted boolean not null default false, created_at timestamptz not null default now());
create table public.inquiry_messages (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, inquiry_id uuid not null references public.inquiries(id) on delete cascade, sender_id uuid references public.profiles(id) on delete set null, body text not null, private boolean not null default false, attachments jsonb not null default '[]', created_at timestamptz not null default now());
create table public.inquiry_internal_notes (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, inquiry_id uuid not null references public.inquiries(id) on delete cascade, author_id uuid references public.profiles(id) on delete set null, body text not null, created_at timestamptz not null default now());
create table public.notifications (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, type text not null, title text not null, message text not null, source_module text, source_entity_type text, source_entity_id uuid, read boolean not null default false, tags text[] not null default '{}', created_at timestamptz not null default now());
create table public.borrowed_assets (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, asset_id uuid not null, asset_type text not null, borrower_type text not null, borrower_id uuid not null, student_id uuid references public.students(id) on delete set null, teacher_id uuid references public.teachers(id) on delete set null, class_id uuid references public.classes(id) on delete set null, issued_by uuid references public.profiles(id) on delete set null, issued_at timestamptz not null default now(), due_at timestamptz, returned_at timestamptz, status text not null, condition_out text, condition_in text, quantity numeric not null default 1, tags text[] not null default '{}');
create table public.activity_events (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, event_type text not null, module text not null, actor_id uuid references public.profiles(id) on delete set null, actor_role text, subject_type text not null, subject_id uuid, related_student_id uuid references public.students(id) on delete set null, related_teacher_id uuid references public.teachers(id) on delete set null, related_class_id uuid references public.classes(id) on delete set null, entity_type text not null, entity_id uuid, tags text[] not null default '{}', metadata jsonb not null default '{}', occurred_at timestamptz not null default now());
create table public.audit_logs (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, actor_id uuid references public.profiles(id) on delete set null, actor_role text, entity_type text not null, entity_id uuid, action text not null, before jsonb, after jsonb, timestamp timestamptz not null default now());

insert into public.roles(code,label) values ('student','Student'),('teacher','Teacher'),('lab_assistant','Lab Assistant'),('librarian','Librarian'),('transport_staff','Transport Staff'),('staff','Staff'),('admin','Admin'),('head_of_school','Head of School') on conflict(code) do nothing;
insert into public.role_permissions(role_id,permission) select id,'*' from public.roles where code='admin' on conflict do nothing;
insert into public.role_permissions(role_id,permission) select id,'lab.manageInventory' from public.roles where code='lab_assistant' on conflict do nothing;
insert into public.role_permissions(role_id,permission) select id,'lab.requests.manage' from public.roles where code='lab_assistant' on conflict do nothing;
insert into public.role_permissions(role_id,permission) select id,'lab.usage.record' from public.roles where code='lab_assistant' on conflict do nothing;
insert into public.role_permissions(role_id,permission) select id,'lab.orders.create' from public.roles where code='lab_assistant' on conflict do nothing;
insert into public.role_permissions(role_id,permission) select id,'lab.orders.receive' from public.roles where code='lab_assistant' on conflict do nothing;
insert into public.role_permissions(role_id,permission) select id,'library.manage' from public.roles where code='librarian' on conflict do nothing;
insert into public.role_permissions(role_id,permission) select id,'transport.view' from public.roles where code='transport_staff' on conflict do nothing;
insert into public.role_permissions(role_id,permission) select id,'transport.manage' from public.roles where code='transport_staff' on conflict do nothing;
insert into public.role_permissions(role_id,permission) select id,'transport.recordArrival' from public.roles where code='transport_staff' on conflict do nothing;
insert into public.role_permissions(role_id,permission) select id,'transport.recordDeparture' from public.roles where code='transport_staff' on conflict do nothing;
insert into public.role_permissions(role_id,permission) select id,'transport.manageNotices' from public.roles where code='transport_staff' on conflict do nothing;
insert into public.role_permissions(role_id,permission) select id,'inquiries.viewAll' from public.roles where code='head_of_school' on conflict do nothing;
insert into public.role_permissions(role_id,permission) select id,'inquiries.reply' from public.roles where code='head_of_school' on conflict do nothing;
insert into public.role_permissions(role_id,permission) select id,'inquiries.assign' from public.roles where code='head_of_school' on conflict do nothing;
insert into public.role_permissions(role_id,permission) select id,'inquiries.manage' from public.roles where code='head_of_school' on conflict do nothing;

create or replace function public.schoolos_has_role(org uuid, allowed public.school_role[]) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.user_roles ur join public.roles r on r.id=ur.role_id where ur.organization_id=org and ur.user_id=auth.uid() and r.code=any(allowed)); $$;
create or replace function public.schoolos_is_member(org uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles p where p.organization_id=org and p.id=auth.uid()); $$;
create or replace function public.schoolos_can_manage_org(org uuid) returns boolean language sql stable security definer set search_path=public as $$ select public.schoolos_has_role(org,array['admin','head_of_school']::public.school_role[]); $$;
create or replace function public.schoolos_has_permission(org uuid, requested text) returns boolean language sql stable security definer set search_path=public as $$ select public.schoolos_can_manage_org(org) or exists(select 1 from public.user_roles ur join public.role_permissions rp on rp.role_id=ur.role_id where ur.organization_id=org and ur.user_id=auth.uid() and (rp.permission='*' or rp.permission=requested)); $$;
create or replace function public.schoolos_is_student_owner(student uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.students s where s.id=student and s.profile_id=auth.uid()); $$;
create or replace function public.schoolos_teacher_can_access_student(org uuid, student uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.class_memberships teacher_membership join public.teachers t on t.id=teacher_membership.teacher_id join public.class_memberships student_membership on student_membership.class_id=teacher_membership.class_id where t.organization_id=org and t.profile_id=auth.uid() and student_membership.student_id=student and teacher_membership.membership_role in ('subject_teacher','class_teacher')); $$;
create or replace function public.schoolos_can_access_student(org uuid, student uuid) returns boolean language sql stable security definer set search_path=public as $$ select public.schoolos_is_student_owner(student) or public.schoolos_teacher_can_access_student(org,student) or public.schoolos_can_manage_org(org); $$;

-- All tables are organization-scoped. Generic policy grants an authenticated
-- member only records in their organization; sensitive tables get narrower policies below.
do $$ declare tbl text; begin foreach tbl in array array['profiles','user_roles','departments','teachers','staff','classes','class_memberships','teacher_class_logs','assignments','resources','lab_items','lab_transactions','lab_orders','library_books','book_copies','book_requests','calendar_events','timetables','exams','projects','project_milestones','maintenance_reports'] loop execute format('alter table public.%I enable row level security',tbl); execute format('create policy org_member_select on public.%I for select using (public.schoolos_is_member(organization_id))',tbl); execute format('create policy org_manager_write on public.%I for all using (public.schoolos_can_manage_org(organization_id)) with check (public.schoolos_can_manage_org(organization_id))',tbl); end loop; end $$;
alter table public.organizations enable row level security;
create policy organizations_member_read on public.organizations for select using (public.schoolos_is_member(id));
alter table public.roles enable row level security;
alter table public.role_permissions enable row level security;
create policy roles_authenticated_read on public.roles for select to authenticated using (true);
create policy role_permissions_authenticated_read on public.role_permissions for select to authenticated using (true);
alter table public.lab_order_items enable row level security;
create policy lab_order_items_member_read on public.lab_order_items for select using (exists(select 1 from public.lab_orders o where o.id=order_id and public.schoolos_is_member(o.organization_id)));
create policy lab_order_items_manager_write on public.lab_order_items for all using (exists(select 1 from public.lab_orders o where o.id=order_id and public.schoolos_can_manage_org(o.organization_id))) with check (exists(select 1 from public.lab_orders o where o.id=order_id and public.schoolos_can_manage_org(o.organization_id)));
alter table public.project_members enable row level security;
create policy project_members_member_read on public.project_members for select using (exists(select 1 from public.projects p where p.id=project_id and public.schoolos_is_member(p.organization_id)));
create policy project_members_manager_write on public.project_members for all using (exists(select 1 from public.projects p where p.id=project_id and public.schoolos_can_manage_org(p.organization_id))) with check (exists(select 1 from public.projects p where p.id=project_id and public.schoolos_can_manage_org(p.organization_id)));

-- Activity and audit history can contain sensitive workflow details. These are
-- intentionally scoped more narrowly than normal organization content.
alter table public.tracked_records enable row level security;
create policy tracked_records_authorized_read on public.tracked_records for select using (
  public.schoolos_can_manage_org(organization_id)
  or (coalesce((visibility->>'studentVisible')::boolean,false) and student_id is not null and public.schoolos_is_student_owner(student_id))
  or (student_id is not null and public.schoolos_teacher_can_access_student(organization_id,student_id))
  or (source_module='Lab' and public.schoolos_has_role(organization_id,array['lab_assistant']::public.school_role[]))
  or (source_module='Library' and public.schoolos_has_role(organization_id,array['librarian']::public.school_role[]))
  or (source_module='Transport' and public.schoolos_has_role(organization_id,array['transport_staff']::public.school_role[]))
);
create policy tracked_records_operational_write on public.tracked_records for all using (
  public.schoolos_has_permission(organization_id,'record.edit')
  or (source_module='Lab' and public.schoolos_has_role(organization_id,array['lab_assistant']::public.school_role[]))
  or (source_module='Library' and public.schoolos_has_role(organization_id,array['librarian']::public.school_role[]))
) with check (public.schoolos_is_member(organization_id));
alter table public.activity_events enable row level security;
create policy activity_events_authorized_read on public.activity_events for select using (
  public.schoolos_can_manage_org(organization_id)
  or (related_student_id is not null and public.schoolos_can_access_student(organization_id,related_student_id))
  or actor_id=auth.uid()
  or (module='Lab' and public.schoolos_has_role(organization_id,array['lab_assistant']::public.school_role[]))
  or (module='Library' and public.schoolos_has_role(organization_id,array['librarian']::public.school_role[]))
);
create policy activity_events_operational_write on public.activity_events for insert with check (public.schoolos_is_member(organization_id));
alter table public.audit_logs enable row level security;
create policy audit_logs_authorized_read on public.audit_logs for select using (public.schoolos_can_manage_org(organization_id) or actor_id=auth.uid());
create policy audit_logs_operational_write on public.audit_logs for insert with check (public.schoolos_is_member(organization_id));

-- Student-linked data is intentionally narrower than organization membership.
alter table public.students enable row level security;
create policy students_authorized_read on public.students for select using (public.schoolos_can_access_student(organization_id,id));
create policy students_manager_write on public.students for all using (public.schoolos_can_manage_org(organization_id)) with check (public.schoolos_can_manage_org(organization_id));
alter table public.attendance_records enable row level security;
create policy attendance_authorized_read on public.attendance_records for select using (public.schoolos_can_access_student(organization_id,student_id));
create policy attendance_teacher_write on public.attendance_records for all using (public.schoolos_teacher_can_access_student(organization_id,student_id) or public.schoolos_can_manage_org(organization_id)) with check (public.schoolos_teacher_can_access_student(organization_id,student_id) or public.schoolos_can_manage_org(organization_id));
alter table public.submissions enable row level security;
create policy submissions_authorized_read on public.submissions for select using (public.schoolos_can_access_student(organization_id,student_id));
create policy submissions_student_write on public.submissions for all using (public.schoolos_is_student_owner(student_id) or public.schoolos_teacher_can_access_student(organization_id,student_id) or public.schoolos_can_manage_org(organization_id)) with check (public.schoolos_is_student_owner(student_id) or public.schoolos_teacher_can_access_student(organization_id,student_id) or public.schoolos_can_manage_org(organization_id));
alter table public.grades enable row level security;
create policy grades_authorized_read on public.grades for select using (public.schoolos_can_access_student(organization_id,student_id));
create policy grades_teacher_write on public.grades for all using (public.schoolos_teacher_can_access_student(organization_id,student_id) or public.schoolos_can_manage_org(organization_id)) with check (public.schoolos_teacher_can_access_student(organization_id,student_id) or public.schoolos_can_manage_org(organization_id));
alter table public.damage_records enable row level security;
create policy damage_authorized_read on public.damage_records for select using ((student_visible and public.schoolos_is_student_owner(student_id)) or public.schoolos_teacher_can_access_student(organization_id,student_id) or public.schoolos_has_role(organization_id,array['lab_assistant','librarian','admin','head_of_school']::public.school_role[]));
create policy damage_operational_write on public.damage_records for all using (public.schoolos_has_role(organization_id,array['lab_assistant','librarian','admin','head_of_school']::public.school_role[])) with check (public.schoolos_has_role(organization_id,array['lab_assistant','librarian','admin','head_of_school']::public.school_role[]));
alter table public.lab_requests enable row level security;
create policy lab_requests_authorized_read on public.lab_requests for select using (requester_id=auth.uid() or public.schoolos_can_access_student(organization_id,student_id) or public.schoolos_has_role(organization_id,array['lab_assistant','admin','head_of_school']::public.school_role[]));
create policy lab_requests_authorized_write on public.lab_requests for all using (requester_id=auth.uid() or public.schoolos_has_role(organization_id,array['lab_assistant','admin','head_of_school']::public.school_role[])) with check (public.schoolos_is_member(organization_id));
alter table public.lab_usage enable row level security;
create policy lab_usage_authorized_read on public.lab_usage for select using ((student_id is not null and public.schoolos_can_access_student(organization_id,student_id)) or public.schoolos_has_role(organization_id,array['lab_assistant','admin','head_of_school']::public.school_role[]));
create policy lab_usage_operational_write on public.lab_usage for all using (public.schoolos_has_role(organization_id,array['lab_assistant','admin','head_of_school']::public.school_role[])) with check (public.schoolos_has_role(organization_id,array['lab_assistant','admin','head_of_school']::public.school_role[]));
alter table public.cas_experiences enable row level security;
create policy cas_authorized_read on public.cas_experiences for select using (public.schoolos_can_access_student(organization_id,student_id));
create policy cas_authorized_write on public.cas_experiences for all using (public.schoolos_is_student_owner(student_id) or public.schoolos_can_manage_org(organization_id)) with check (public.schoolos_is_student_owner(student_id) or public.schoolos_can_manage_org(organization_id));
alter table public.transport_notices enable row level security;
create policy transport_authorized_read on public.transport_notices for select using ((student_visible and public.schoolos_is_student_owner(student_id)) or public.schoolos_teacher_can_access_student(organization_id,student_id) or public.schoolos_has_role(organization_id,array['transport_staff','admin','head_of_school']::public.school_role[]));
create policy transport_authorized_write on public.transport_notices for all using (public.schoolos_teacher_can_access_student(organization_id,student_id) or public.schoolos_has_role(organization_id,array['transport_staff','admin','head_of_school']::public.school_role[])) with check (public.schoolos_is_member(organization_id));
alter table public.buses enable row level security;
alter table public.bus_arrival_records enable row level security;
alter table public.bus_departure_records enable row level security;
alter table public.transport_activity enable row level security;
create policy buses_transport_read on public.buses for select using (public.schoolos_has_role(organization_id,array['transport_staff','admin','head_of_school']::public.school_role[]));
create policy buses_transport_write on public.buses for all using (public.schoolos_has_role(organization_id,array['transport_staff','admin','head_of_school']::public.school_role[])) with check (public.schoolos_has_role(organization_id,array['transport_staff','admin','head_of_school']::public.school_role[]));
create policy arrival_transport_read on public.bus_arrival_records for select using (public.schoolos_has_role(organization_id,array['transport_staff','admin','head_of_school']::public.school_role[]));
create policy arrival_transport_write on public.bus_arrival_records for all using (public.schoolos_has_role(organization_id,array['transport_staff','admin','head_of_school']::public.school_role[])) with check (public.schoolos_has_role(organization_id,array['transport_staff','admin','head_of_school']::public.school_role[]));
create policy departure_transport_read on public.bus_departure_records for select using (public.schoolos_has_role(organization_id,array['transport_staff','admin','head_of_school']::public.school_role[]));
create policy departure_transport_write on public.bus_departure_records for all using (public.schoolos_has_role(organization_id,array['transport_staff','admin','head_of_school']::public.school_role[])) with check (public.schoolos_has_role(organization_id,array['transport_staff','admin','head_of_school']::public.school_role[]));
create policy activity_transport_read on public.transport_activity for select using (public.schoolos_has_role(organization_id,array['transport_staff','admin','head_of_school']::public.school_role[]));
create policy activity_transport_write on public.transport_activity for insert with check (public.schoolos_has_role(organization_id,array['transport_staff','admin','head_of_school']::public.school_role[]));
alter table public.notifications enable row level security;
create policy notifications_own_read on public.notifications for select using (user_id=auth.uid());
create policy notifications_manager_write on public.notifications for all using (public.schoolos_can_manage_org(organization_id)) with check (public.schoolos_can_manage_org(organization_id));
alter table public.borrowed_assets enable row level security;
create policy borrowed_assets_authorized_read on public.borrowed_assets for select using ((student_id is not null and public.schoolos_can_access_student(organization_id,student_id)) or public.schoolos_has_role(organization_id,array['librarian','lab_assistant','admin','head_of_school']::public.school_role[]));
create policy borrowed_assets_operational_write on public.borrowed_assets for all using (public.schoolos_has_role(organization_id,array['librarian','lab_assistant','admin','head_of_school']::public.school_role[])) with check (public.schoolos_has_role(organization_id,array['librarian','lab_assistant','admin','head_of_school']::public.school_role[]));

alter table public.student_records enable row level security;
create policy student_records_student_read on public.student_records for select using (student_visible and exists(select 1 from public.students s where s.id=student_id and s.profile_id=auth.uid()));
create policy student_records_teacher_read on public.student_records for select using (not restricted and public.schoolos_has_role(organization_id,array['teacher']::public.school_role[]));
create policy student_records_sensitive_permission on public.student_records for select using (public.schoolos_has_permission(organization_id,'student.records.sensitive'));
create policy student_records_staff_write on public.student_records for all using (public.schoolos_has_permission(organization_id,'record.edit')) with check (public.schoolos_has_permission(organization_id,'record.edit'));
alter table public.inquiries enable row level security;
alter table public.inquiry_messages enable row level security;
alter table public.inquiry_internal_notes enable row level security;
create policy inquiries_participant_read on public.inquiries for select using ((not restricted and public.schoolos_is_member(organization_id)) or created_by=auth.uid() or assigned_to=auth.uid() or public.schoolos_has_permission(organization_id,'inquiries.restricted'));
create policy inquiries_participant_write on public.inquiries for all using (created_by=auth.uid() or assigned_to=auth.uid() or public.schoolos_has_permission(organization_id,'inquiries.manage')) with check (public.schoolos_is_member(organization_id));
create policy inquiry_messages_participant_read on public.inquiry_messages for select using (exists(select 1 from public.inquiries i where i.id=inquiry_id and ((not i.restricted and not private and public.schoolos_is_member(i.organization_id)) or i.created_by=auth.uid() or i.assigned_to=auth.uid() or public.schoolos_has_permission(i.organization_id,'inquiries.restricted'))));
create policy inquiry_messages_participant_write on public.inquiry_messages for insert with check (exists(select 1 from public.inquiries i where i.id=inquiry_id and (i.created_by=auth.uid() or i.assigned_to=auth.uid() or public.schoolos_has_permission(i.organization_id,'inquiries.manage'))));
create policy inquiry_notes_staff_read on public.inquiry_internal_notes for select using (public.schoolos_has_permission(organization_id,'inquiries.viewAll') or author_id=auth.uid());
create policy inquiry_notes_staff_write on public.inquiry_internal_notes for all using (public.schoolos_has_permission(organization_id,'inquiries.manage')) with check (public.schoolos_has_permission(organization_id,'inquiries.manage'));

insert into storage.buckets(id,name,public) values ('assignment-submissions','assignment-submissions',false),('class-resources','class-resources',false),('project-files','project-files',false),('cas-evidence','cas-evidence',false),('inquiry-attachments','inquiry-attachments',false),('maintenance-images','maintenance-images',false),('lab-images','lab-images',false),('library-covers','library-covers',true),('documents','documents',false) on conflict(id) do nothing;
drop policy if exists schoolos_storage_read on storage.objects;
drop policy if exists schoolos_storage_write on storage.objects;
create policy schoolos_storage_read on storage.objects for select using (bucket_id='library-covers' or (auth.role()='authenticated' and exists(select 1 from public.profiles p where p.id=auth.uid() and storage.objects.name like p.organization_id::text || '/%')));
create policy schoolos_storage_write on storage.objects for insert with check (auth.role()='authenticated' and bucket_id in ('assignment-submissions','class-resources','project-files','cas-evidence','inquiry-attachments','maintenance-images','lab-images','library-covers','documents') and exists(select 1 from public.profiles p where p.id=auth.uid() and storage.objects.name like p.organization_id::text || '/%'));
